## Pagerank
PageRank bekerja dengan menghitung jumlah dan kualitas tautan ke suatu halaman untuk menentukan perkiraan kasar seberapa penting situs web tersebut. Asumsi yang mendasarinya adalah bahwa situs web yang lebih penting cenderung menerima lebih banyak tautan dari situs web lainnya

In [ ]:
import numpy as np
A = np.array([[0,0,1,1/2], [1/3, 0 ,0 ,0], [1/3,1/2,0,1/2],[1/3,1/2,0,0]])
v = np.array([[0.25], [0.25], [0.25], [0.25]])
print ('A x v=\n', A@v)
print ('A^2 x v=\n', A@A@v)
print ('A x (Av)=\n', A@(A@v))
print ('A^3 x v=\n', A@A@A@v)
print ('A^4 x v=\n', A@A@A@A@v)
print ('A^5 x v=\n', A@A@A@A@A@v)
print ('A^6 x v=\n', A@A@A@A@A@A@v)
print ('A^7 x v=\n', A@A@A@A@A@A@A@v)
print ('A^8 x v=\n', A@A@A@A@A@A@A@A@v)

A x v=
 [[0.375     ]
 [0.08333333]
 [0.33333333]
 [0.20833333]]
A^2 x v=
 [[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]
A x (Av)=
 [[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]
A^3 x v=
 [[0.35416667]
 [0.14583333]
 [0.29166667]
 [0.20833333]]
A^4 x v=
 [[0.39583333]
 [0.11805556]
 [0.29513889]
 [0.19097222]]
A^5 x v=
 [[0.390625  ]
 [0.13194444]
 [0.28645833]
 [0.19097222]]
A^6 x v=
 [[0.38194444]
 [0.13020833]
 [0.29166667]
 [0.19618056]]
A^7 x v=
 [[0.38975694]
 [0.12731481]
 [0.29050926]
 [0.19241898]]
A^8 x v=
 [[0.38671875]
 [0.12991898]
 [0.28978588]
 [0.19357639]]


In [ ]:
import numpy as np
A = np.array([[0,0,1,1/2], [1/3, 0 ,0 ,0], [1/3,1/2,0,1/2],[1/3,1/2,0,0]])
v = np.array([[0.20], [0.30], [0.20], [0.30]])
print ('A x v=\n', A@v)
print ('A^2 x v=\n', A@A@v)
print ('A x (Av)=\n', A@(A@v))

A x v=
 [[0.35      ]
 [0.06666667]
 [0.36666667]
 [0.21666667]]
A^2 x v=
 [[0.475     ]
 [0.11666667]
 [0.25833333]
 [0.15      ]]
A x (Av)=
 [[0.475     ]
 [0.11666667]
 [0.25833333]
 [0.15      ]]


previous_result = matriks v

result = matriks A x previous_result

tolerance = 0.01

Rumus = (result - previous_result) ** 2 (rumus tersebut berlaku selama hasil dari rumus tersebut kurang dari tolerance)

In [ ]:
import numpy as np

A = np.array([[0, 0, 1, 1/2],
              [1/3, 0, 0, 0],
              [1/3, 1/2, 0, 1/2],
              [1/3, 1/2, 0, 0]])

v = np.array([[0.25], [0.25], [0.25], [0.25]])

previous_result = v
tolerance = 0.01  # Ubah nilai toleransi menjadi 0.01

for i in range(1, 100):  # Batasi jumlah iterasi untuk mencegah perulangan tak terbatas
    result = A @ previous_result
    print(f"(A^{i})v = \n", result)

    # Cek kondisi berhenti
    if np.all(np.abs(result - previous_result) <= tolerance):
        if np.sqrt(np.sum((result - previous_result) ** 2)) < tolerance:
          print(f"\nPerkalian matriks konvergen pada iterasi ke-{i}.")
          break

    previous_result = result

(A^1)v = 
 [[0.375     ]
 [0.08333333]
 [0.33333333]
 [0.20833333]]
(A^2)v = 
 [[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]
(A^3)v = 
 [[0.35416667]
 [0.14583333]
 [0.29166667]
 [0.20833333]]
(A^4)v = 
 [[0.39583333]
 [0.11805556]
 [0.29513889]
 [0.19097222]]
(A^5)v = 
 [[0.390625  ]
 [0.13194444]
 [0.28645833]
 [0.19097222]]
(A^6)v = 
 [[0.38194444]
 [0.13020833]
 [0.29166667]
 [0.19618056]]
(A^7)v = 
 [[0.38975694]
 [0.12731481]
 [0.29050926]
 [0.19241898]]

Perkalian matriks konvergen pada iterasi ke-7.


### Algoritma
Berikut adalah langkah-langkah dasar dari algoritma PageRank:

1. Model Surfer Acak (Random Surfer Model): Algoritma ini mengasumsikan bahwa pengguna internet (surfer) secara acak mengklik tautan dari satu halaman ke halaman lain. Probabilitas halaman untuk dikunjungi mencerminkan pentingnya halaman tersebut.

2. Distribusi Tautan: Setiap halaman membagi pentingnya (ranking) secara merata ke semua halaman yang ditautkannya. Jika sebuah halaman memiliki banyak tautan keluar, maka setiap tautan akan mendapatkan bagian penting yang lebih kecil.

3. Faktor Damping: Untuk mencegah semua ranking terkonsentrasi pada beberapa halaman, digunakan faktor damping (biasanya sekitar 0.85). Ini mengasumsikan bahwa surfer tidak hanya mengklik tautan, tetapi juga bisa melompat ke halaman acak dengan probabilitas tertentu (1 - d).

4. Perhitungan Iteratif: PageRank dihitung secara iteratif, di mana setiap iterasi memperbarui ranking berdasarkan ranking yang diterima dari halaman lain. Proses ini diulang hingga ranking stabil dan tidak berubah signifikan antar iterasi.

Untuk menentukan pagerank sebuah halaman web, Google menggunakan algoritma sebagai berikut :

       
       PR(A) = (1-d) / N + d ( ( PR(T1) / C(T1) ) + … + ( PR(Tn) / C(Tn) ) )

Keterangan :

PR(A) adalah Pagerank halaman A

PR(T1) adalah Pagerank halaman T1 yang mengacu ke halaman A (yang dimaksud adalah pagerank dari backlink yang mengarah ke situs A)

C(T1) adalah jumlah link keluar (outbound link) pada halaman T1 (yang dimaksud adalah jumlah link keluar dari backlink yang mengarah ke situs A)

d adalah damping factor yang bisa diberi antara 0 dan 1

N adalah jumlah keseluruhan halaman web yang terindeks oleh Google



In [2]:
import numpy as np

def calculate_pagerank(links, damping_factor=0.85, convergence_threshold=1e-5):
    n_pages = len(links)
    M = np.zeros((n_pages, n_pages))

    # Membangun matriks transisi
    for page, outbound_links in enumerate(links):
        if not outbound_links:
            # Distribusi seragam jika tidak ada tautan keluar
            M[page] = np.ones(n_pages) / n_pages
        else:
            # Setiap tautan keluar mendapat bagian yang sama dari pentingnya halaman
            M[page, outbound_links] = 1 / len(outbound_links)

    # Menghitung matriks transisi dengan faktor damping
    M = damping_factor * M + (1 - damping_factor) / n_pages * np.ones((n_pages, n_pages))

    # Inisialisasi vektor peringkat
    pagerank_vector = np.ones(n_pages) / n_pages

    # Iterasi hingga konvergensi
    while True:
        new_pagerank_vector = M @ pagerank_vector
        if np.linalg.norm(new_pagerank_vector - pagerank_vector, 1) < convergence_threshold:
            break
        pagerank_vector = new_pagerank_vector

    return pagerank_vector

# Contoh penggunaan
links_example = [
    [1, 2],  # Halaman 0 memiliki tautan ke halaman 1 dan 2
    [2],     # Halaman 1 memiliki tautan ke halaman 2
    [0]      # Halaman 2 memiliki tautan ke halaman 0
]

pagerank_scores = calculate_pagerank(links_example)
print(pagerank_scores)


[0.33333333 0.33333333 0.33333333]


Dalam contoh ini, links adalah daftar yang berisi daftar indeks halaman yang ditautkan oleh setiap halaman. Fungsi calculate_pagerank akan menghitung skor PageRank untuk setiap halaman berdasarkan struktur tautan yang diberikan. damping_factor adalah faktor damping ( d ), dan convergence_threshold adalah nilai ambang batas untuk menentukan konvergensi algoritma.

Kode ini akan menghasilkan vektor skor PageRank yang menunjukkan pentingnya relatif setiap halaman dalam daftar links.

### Komputasi untuk menghitung pagerank (Gunakan error toleransi)

In [1]:
import numpy as np

def pagerank(M, num_iterations: int = 100, d: float = 0.85):
    """PageRank: The calculation of ranked web pages."""
    N = M.shape[1]
    v = np.random.rand(N, 1)
    v = v / np.linalg.norm(v, 1)
    M_hat = (d * M + (1 - d) / N)
    for i in range(num_iterations):
        v_prev = v
        v = M_hat @ v
        # Periksa error toleransi
        if np.linalg.norm(v - v_prev, 1) < 1e-5:
            break
    return v

# Contoh matriks M
M = np.array([[0, 0, 1],
              [1, 0, 0],
              [0, 1, 0]])

print(pagerank(M))


[[0.33333481]
 [0.33333034]
 [0.33333485]]


Dalam kode ini, M adalah matriks transisi, num_iterations adalah jumlah iterasi maksimum, dan d adalah faktor damping yang biasanya diatur ke 0.85. Fungsi pagerank menghitung vektor peringkat halaman, dan loop iterasi akan berhenti jika perbedaan antara vektor peringkat pada iterasi berturut-turut kurang dari error toleransi yang ditentukan (dalam hal ini, 1e-5). 1e-5 adalah notasi ilmiah yang menggambarkan 0.00001 dalam bentuk bilangan desimal. Dalam matematika dan ilmu komputer, notasi ini digunakan untuk menyatakan angka yang sangat kecil atau mendekati nol. Dalam konteks algoritma PageRank yang sebelumnya saya berikan, 1e-5 digunakan sebagai error toleransi. Artinya, iterasi akan berhenti ketika perbedaan antara vektor peringkat pada iterasi berturut-turut kurang dari 0.00001