## Pagerank
PageRank bekerja dengan menghitung jumlah dan kualitas tautan ke suatu halaman untuk menentukan perkiraan kasar seberapa penting situs web tersebut. Asumsi yang mendasarinya adalah bahwa situs web yang lebih penting cenderung menerima lebih banyak tautan dari situs web lainnya

In [ ]:
import numpy as np
A = np.array([[0,0,1,1/2], [1/3, 0 ,0 ,0], [1/3,1/2,0,1/2],[1/3,1/2,0,0]])
v = np.array([[0.25], [0.25], [0.25], [0.25]])
print ('A x v=\n', A@v)
print ('A^2 x v=\n', A@A@v)
print ('A x (Av)=\n', A@(A@v))
print ('A^3 x v=\n', A@A@A@v)
print ('A^4 x v=\n', A@A@A@A@v)
print ('A^5 x v=\n', A@A@A@A@A@v)
print ('A^6 x v=\n', A@A@A@A@A@A@v)
print ('A^7 x v=\n', A@A@A@A@A@A@A@v)
print ('A^8 x v=\n', A@A@A@A@A@A@A@A@v)

A x v=
 [[0.375     ]
 [0.08333333]
 [0.33333333]
 [0.20833333]]
A^2 x v=
 [[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]
A x (Av)=
 [[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]
A^3 x v=
 [[0.35416667]
 [0.14583333]
 [0.29166667]
 [0.20833333]]
A^4 x v=
 [[0.39583333]
 [0.11805556]
 [0.29513889]
 [0.19097222]]
A^5 x v=
 [[0.390625  ]
 [0.13194444]
 [0.28645833]
 [0.19097222]]
A^6 x v=
 [[0.38194444]
 [0.13020833]
 [0.29166667]
 [0.19618056]]
A^7 x v=
 [[0.38975694]
 [0.12731481]
 [0.29050926]
 [0.19241898]]
A^8 x v=
 [[0.38671875]
 [0.12991898]
 [0.28978588]
 [0.19357639]]


In [ ]:
import numpy as np
A = np.array([[0,0,1,1/2], [1/3, 0 ,0 ,0], [1/3,1/2,0,1/2],[1/3,1/2,0,0]])
v = np.array([[0.20], [0.30], [0.20], [0.30]])
print ('A x v=\n', A@v)
print ('A^2 x v=\n', A@A@v)
print ('A x (Av)=\n', A@(A@v))

A x v=
 [[0.35      ]
 [0.06666667]
 [0.36666667]
 [0.21666667]]
A^2 x v=
 [[0.475     ]
 [0.11666667]
 [0.25833333]
 [0.15      ]]
A x (Av)=
 [[0.475     ]
 [0.11666667]
 [0.25833333]
 [0.15      ]]


## Perkalian matriks konvergen

previous_result = matriks v

result = matriks A x previous_result

tolerance = 0.01

Rumus = (result - previous_result) ** 2 (rumus tersebut berlaku selama hasil dari rumus tersebut kurang dari tolerance)

In [ ]:
import numpy as np

A = np.array([[0, 0, 1, 1/2],
              [1/3, 0, 0, 0],
              [1/3, 1/2, 0, 1/2],
              [1/3, 1/2, 0, 0]])

v = np.array([[0.25], [0.25], [0.25], [0.25]])

previous_result = v
tolerance = 0.01  # Ubah nilai toleransi menjadi 0.01

for i in range(1, 100):  # Batasi jumlah iterasi untuk mencegah perulangan tak terbatas
    result = A @ previous_result
    print(f"(A^{i})v = \n", result)

    # Cek kondisi berhenti
    if np.all(np.abs(result - previous_result) <= tolerance):
        if np.sqrt(np.sum((result - previous_result) ** 2)) < tolerance:
          print(f"\nPerkalian matriks konvergen pada iterasi ke-{i}.")
          break

    previous_result = result

(A^1)v = 
 [[0.375     ]
 [0.08333333]
 [0.33333333]
 [0.20833333]]
(A^2)v = 
 [[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]
(A^3)v = 
 [[0.35416667]
 [0.14583333]
 [0.29166667]
 [0.20833333]]
(A^4)v = 
 [[0.39583333]
 [0.11805556]
 [0.29513889]
 [0.19097222]]
(A^5)v = 
 [[0.390625  ]
 [0.13194444]
 [0.28645833]
 [0.19097222]]
(A^6)v = 
 [[0.38194444]
 [0.13020833]
 [0.29166667]
 [0.19618056]]
(A^7)v = 
 [[0.38975694]
 [0.12731481]
 [0.29050926]
 [0.19241898]]

Perkalian matriks konvergen pada iterasi ke-7.


### Algoritma
Berikut adalah langkah-langkah dasar dari algoritma PageRank:

1. Model Surfer Acak (Random Surfer Model): Algoritma ini mengasumsikan bahwa pengguna internet (surfer) secara acak mengklik tautan dari satu halaman ke halaman lain. Probabilitas halaman untuk dikunjungi mencerminkan pentingnya halaman tersebut.

2. Distribusi Tautan: Setiap halaman membagi pentingnya (ranking) secara merata ke semua halaman yang ditautkannya. Jika sebuah halaman memiliki banyak tautan keluar, maka setiap tautan akan mendapatkan bagian penting yang lebih kecil.

3. Faktor Damping: Untuk mencegah semua ranking terkonsentrasi pada beberapa halaman, digunakan faktor damping (biasanya sekitar 0.85). Ini mengasumsikan bahwa surfer tidak hanya mengklik tautan, tetapi juga bisa melompat ke halaman acak dengan probabilitas tertentu (1 - d).

4. Perhitungan Iteratif: PageRank dihitung secara iteratif, di mana setiap iterasi memperbarui ranking berdasarkan ranking yang diterima dari halaman lain. Proses ini diulang hingga ranking stabil dan tidak berubah signifikan antar iterasi.

Untuk menentukan pagerank sebuah halaman web, Google menggunakan algoritma sebagai berikut :

       
       PR(A) = (1-d) / N + d ( ( PR(T1) / C(T1) ) + … + ( PR(Tn) / C(Tn) ) )

Keterangan :

PR(A) adalah Pagerank halaman A

PR(T1) adalah Pagerank halaman T1 yang mengacu ke halaman A (yang dimaksud adalah pagerank dari backlink yang mengarah ke situs A)

C(T1) adalah jumlah link keluar (outbound link) pada halaman T1 (yang dimaksud adalah jumlah link keluar dari backlink yang mengarah ke situs A)

d adalah damping factor yang bisa diberi antara 0 dan 1

N adalah jumlah keseluruhan halaman web yang terindeks oleh Google



### Komputasi untuk menghitung pagerank (Gunakan error toleransi)

1. Toleransi kesalahan mengacu pada sejauh mana algoritma dapat mengatasi ketidakpastian dalam perhitungan.

2. Dalam konteks PageRank, toleransi kesalahan dapat diterapkan dengan membatasi jumlah iterasi atau menghentikan iterasi ketika perubahan skor PageRank sudah cukup kecil.

3. Dengan memperkenalkan toleransi kesalahan, kita dapat mengurangi waktu komputasi dan memori yang dibutuhkan.