# DETERMINANT MATRIX
Determinan matriks adalah nilai skalar yang bisa dihitung dari elemen-elemen sebuah matriks persegi. Matriks persegi adalah matriks yang jumlah baris dan kolomnya sama, seperti 2x2 atau 3x3

Determinan matriks ordo(2 x 2)
$$
\begin{equation*}
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
det (A) = ad - bc
\end{equation*}
$$

Determinan matriks ordo (3 x 3)
$$
\begin{equation*}
A=
\begin{bmatrix}
p&q&r\\
s&t&u\\
v&w&x\
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
det (A) =ptx + quv + rst - vtr - wuq - xsq
\end{equation*}
$$


## Syarat-syarat Determinan Matriks
Determinan Matriks Persegi yaitu determinan yang hanya bisa dihitung untuk matriks persegi, yaitu matriks dengan jumlah baris dan kolom yang sama

## Fungsi Determinan Matriks

### 1. Determinan dari matriks identitas akan mengkasilkan 1

In [ ]:
import numpy as np
A = np.array ([[1, 0], [0,1]])
determinan = np.linalg.det(A)
print (A, "\n")
print("Determinan dari matriks identitas ordo (2x2) adalah:", int(determinan))

B= np.array ([[1,0,0], [0,1,0], [0,0,1]])
determinan_B = np.linalg.det(B)
print (B, "\n")
print("Determinan dari matriks identitas ordo (3X3) adalah:", int(determinan_B))

[[1 0]
 [0 1]] 

Determinan dari matriks identitas ordo (2x2) adalah: 1
[[1 0 0]
 [0 1 0]
 [0 0 1]] 

Determinan ari matriks identitas ordo (3X3) adalah: 1


### 2. Menukar baris pada suatu matriks akan mengakibatkan perubahan tanda pada hasil determinannya

In [ ]:
import numpy as np
C = np.array ([[1,2,1], [3,1,2], [2,1,2]])
determinan = np.linalg.det(C)
print (C, "\n")
print("Determinan matriks adalah:", int(determinan))

D = np.array ([[3,1,2], [1,2,1], [2,1,2]])
determinan_D = np.linalg.det(D)
print (D, "\n")
print("Determinan matriks jika dirubah letak barisnya adalah:", int(determinan_D))

[[1 2 1]
 [3 1 2]
 [2 1 2]] 

Determinan matriks adalah: -3
[[3 1 2]
 [1 2 1]
 [2 1 2]] 

Determinan matriks jika dirubah letak barisnya adalah: 3


### 3. Dua baris atau kolom yang elemennya sama/kelipatannya, maka determinan matriksnya = 0

In [1]:
import numpy as np
E =np.array  ([[1,2,1], [2,4,2], [2,1,2]])
determinan = np.linalg.det(E)
print (E, "\n")
print("Determinan matriks jika barisnya memiliki kelipatan yang sama adalah:", int(determinan))

F =np.array  ([[1,2,1], [2,4,2], [2,4,2]])
determinan_F = np.linalg.det(F)
print (F, "\n")
print("Determinan matriks jika kolomnya memiliki kelipatan yang sama adalah:", int(determinan_F))

[[1 2 1]
 [2 4 2]
 [2 1 2]] 

Determinan matriks jika barisnya memiliki kelipatan yang sama adalah: 0
[[1 2 1]
 [2 4 2]
 [2 4 2]] 

Determinan matriks jika kolomnya memiliki kelipatan yang sama adalah: 0


### 4.
$
\begin{equation*}
(A)=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$

 jika matriks ( A ) dikalikan dengan skalar ( x ), lalu menghasilkan matriks ( B ), maka determinan matriks ( B ), akan sama dengan ( x^n ) dikalikan dengan ( det(A) ), di mana ( n ) adalah ordo matriks. Ini berarti jika ( x ) dikuadratkan dan kemudian dikalikan dengan determinan matriks ( A ), hasilnya akan memberikan determinan matriks ( B ), asalkan ( n ) adalah ordo kuadrat dari matriks tersebut.

$
\begin{equation*}
(B)=
\begin{bmatrix}
X*a&X*b\\
X*c&X*d
\end{bmatrix}
\end{equation*}
$

Matriks tersebut memiliki ordo (2x2). Kemudian mencari determinan matriks A dan B. maka akan menghasilkan sebuah fungsi yaitu

$$ det(B) = X^n * det(A)$$

In [1]:
import numpy as np
A =np.array  ([[3,4], [2,1]])
determinan = np.linalg.det(A)
print (A, "\n")
print("Determinan dari matriks A adalah:", int(determinan))

H = np.array ([[6,8], [4,2]])
determinan_H = np.linalg.det(H)
print (H, "\n")
print("Determinan dari matriks H adalah:", int(determinan_H.round()))

print ('det(B) = X^n * det(A)= 2^2 * (-5)= 4 * (-5)= (-20)')

[[3 4]
 [2 1]] 

Determinan dari matriks A adalah: -5
[[6 8]
 [4 2]] 

Determinan dari matriks H adalah: -20
det(B) = X^n * det(A)= 2^2 * (-5)= 4 * (-5)= (-20)


### 5.
$
\begin{equation*}
t * det(A)=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$

  hasilnya akan sama dengan

$
\begin{equation*}
det(A)=
\begin{bmatrix}
t*a&t*b\\
c&d
\end{bmatrix}
\end{equation*}
$

In [6]:
import numpy as np
T= 2
A =np.array  ([[3,4], [2,1]])
determinan = np.linalg.det(A)
print (A, "\n")
hasil = determinan * T
print("Determinan dari matriks A adalah:", int(hasil.round()))

I = np.array ([[3*T,4*T], [2,1]])
determinan_I = np.linalg.det(I)
print (I, "\n")
print("Determinan dari matriks I adalah:", int(determinan_I.round()))

[[3 4]
 [2 1]] 

Determinan dari matriks A adalah: -10
[[6 8]
 [2 1]] 

Determinan dari matriks I adalah: -10


### 6. Det (A) = det (B) + det (C)

In [5]:
import numpy as np
A = np.array ([[7,5], [2,1]])
determinan = np.linalg.det(A)
print (A, "\n")
print("Determinan dari matriks A adalah:", int(determinan.round()))
B= np.array ([[3,4], [2,1]])
determinan_B = np.linalg.det(B)
print (B, "\n")
print("Determinan dari matriks B adalah:", int(determinan_B.round()))
C = np.array ([[4,1], [2,1]])
determinan_C = np.linalg.det(C)
print (C, "\n")
print("Determinan dari matriks C adalah:", int(determinan_C.round()))

[[7 5]
 [2 1]] 

Determinan dari matriks A adalah: -3
[[3 4]
 [2 1]] 

Determinan dari matriks B adalah: -5
[[4 1]
 [2 1]] 

Determinan dari matriks C adalah: 2


### 7.  Mengalikan setiap entri di kolom pertama dengan kofaktor yang sesuai, dan kemudian menjumlahkan hasilnya

In [ ]:
import numpy as np
A = np.array ([[1,3,2], [0,2,2], [0,0,1]])
determinan = np.linalg.det(A)
print (A, "\n")
print("Determinan matriks adalah:", int(determinan))

[[1 3 2]
 [0 2 2]
 [0 0 1]] 

Determinan matriks adalah: 2


In [ ]:
import numpy as np
A = np.array ([[2,1,5], [0,4,1], [0,0,2]])
determinan = np.linalg.det(A)
print (A, "\n")
print("Determinan matriks adalah:", int(determinan))

[[2 1 5]
 [0 4 1]
 [0 0 2]] 

Determinan matriks adalah: 15
