# DETERMINANT MATRIX
Determinan matriks adalah nilai skalar yang bisa dihitung dari elemen-elemen sebuah matriks persegi. Matriks persegi adalah matriks yang jumlah baris dan kolomnya sama, seperti 2x2 atau 3x3

Determinan matriks ordo(2 x 2)
$$
\begin{equation*}
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
det (A) = ad - bc
\end{equation*}
$$

Determinan matriks ordo (3 x 3)
$$
\begin{equation*}
A=
\begin{bmatrix}
p&q&r\\
s&t&u\\
v&w&x\
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
det (A) =ptx + quv + rst - vtr - wuq - xsq
\end{equation*}
$$


## Syarat-syarat Determinan Matriks
Determinan Matriks Persegi yaitu determinan yang hanya bisa dihitung untuk matriks persegi, yaitu matriks dengan jumlah baris dan kolom yang sama

## Fungsi Determinan Matriks

### 1. Determinan dari matriks identitas akan mengkasilkan 1

In [ ]:
import numpy as np
A = np.array ([[1, 0], [0,1]])
determinan = np.linalg.det(A)
print (A, "\n")
print("Determinan dari matriks identitas ordo (2x2) adalah:", int(determinan))

B= np.array ([[1,0,0], [0,1,0], [0,0,1]])
determinan_B = np.linalg.det(B)
print (B, "\n")
print("Determinan dari matriks identitas ordo (3X3) adalah:", int(determinan_B))

[[1 0]
 [0 1]] 

Determinan dari matriks identitas ordo (2x2) adalah: 1
[[1 0 0]
 [0 1 0]
 [0 0 1]] 

Determinan ari matriks identitas ordo (3X3) adalah: 1


### 2. Menukar baris pada suatu matriks akan mengakibatkan perubahan tanda pada hasil determinannya

In [ ]:
import numpy as np
C = np.array ([[1,2,1], [3,1,2], [2,1,2]])
determinan = np.linalg.det(C)
print (C, "\n")
print("Determinan matriks adalah:", int(determinan))

D = np.array ([[3,1,2], [1,2,1], [2,1,2]])
determinan_D = np.linalg.det(D)
print (D, "\n")
print("Determinan matriks jika dirubah letak barisnya adalah:", int(determinan_D))

[[1 2 1]
 [3 1 2]
 [2 1 2]] 

Determinan matriks adalah: -3
[[3 1 2]
 [1 2 1]
 [2 1 2]] 

Determinan matriks jika dirubah letak barisnya adalah: 3


### 3. Dua baris atau kolom yang elemennya sama/kelipatannya, maka determinan matriksnya = 0

In [ ]:
import numpy as np
E =np.array  ([[1,2,1], [2,4,2], [2,1,2]])
determinan = np.linalg.det(E)
print (E, "\n")
print("Determinan matriks jika barisnya memiliki kelipatan yang sama adalah:", int(determinan))

F =np.array  ([[1,2,1], [2,4,2], [2,4,2]])
determinan_F = np.linalg.det(F)
print (F, "\n")
print("Determinan matriks jika kolomnya memiliki kelipatan yang sama adalah:", int(determinan_F))

[[1 2 1]
 [2 4 2]
 [2 1 2]] 

Determinan matriks jika barisnya memiliki kelipatan yang sama adalah: 0
[[1 2 1]
 [2 4 2]
 [2 4 2]] 

Determinan matriks jika kolomnya memiliki kelipatan yang sama adalah: 0


### 4.

$$
\begin{equation*}
(A)=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$$

 jika matriks ( A ) dikalikan dengan skalar ( x ), lalu menghasilkan matriks ( B ), maka determinan matriks ( B ), akan sama dengan ( x^n ) dikalikan dengan ( det(A) ), di mana ( n ) adalah ordo matriks. Ini berarti jika ( x ) dikuadratkan dan kemudian dikalikan dengan determinan matriks ( A ), hasilnya akan memberikan determinan matriks ( B ), asalkan ( n ) adalah ordo kuadrat dari matriks tersebut.

$$
\begin{equation*}
(B)=
\begin{bmatrix}
X*a&X*b\\
X*c&X*d
\end{bmatrix}
\end{equation*}
$$

Matriks tersebut memiliki ordo (2x2). Kemudian mencari determinan matriks A dan B. maka akan menghasilkan sebuah fungsi yaitu

$$
\begin{equation*}
det(B) = X^n * det(A)
\end{equation*}
$$

In [ ]:
import numpy as np
A =np.array  ([[3,4], [2,1]])
determinan = np.linalg.det(A)
print (A, "\n")
print("Determinan dari matriks A adalah:", int(determinan))

H = np.array ([[6,8], [4,2]])
determinan_H = np.linalg.det(H)
print (H, "\n")
print("Determinan dari matriks H adalah:", int(determinan_H.round()))

print ('det(B) = X^n * det(A)= 2^2 * (-5)= 4 * (-5)= (-20)')

[[3 4]
 [2 1]] 

Determinan dari matriks A adalah: -5
[[6 8]
 [4 2]] 

Determinan dari matriks H adalah: -20
det(B) = X^n * det(A)= 2^2 * (-5)= 4 * (-5)= (-20)


### 5.
$
\begin{equation*}
t * det(A)=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$

  hasilnya akan sama dengan

$
\begin{equation*}
det(A)=
\begin{bmatrix}
t*a&t*b\\
c&d
\end{bmatrix}
\end{equation*}
$

In [ ]:
import numpy as np
T= 2
A =np.array  ([[3,4], [2,1]])
determinan = np.linalg.det(A)
print (A, "\n")
hasil = determinan * T
print("Determinan dari matriks A adalah:", int(hasil.round()))

I = np.array ([[3*T,4*T], [2,1]])
determinan_I = np.linalg.det(I)
print (I, "\n")
print("Determinan dari matriks I adalah:", int(determinan_I.round()))

[[3 4]
 [2 1]] 

Determinan dari matriks A adalah: -10
[[6 8]
 [2 1]] 

Determinan dari matriks I adalah: -10


### 6. Det (A) = det (B) + det (C)

In [ ]:
import numpy as np
A = np.array ([[7,5], [2,1]])
determinan = np.linalg.det(A)
print (A, "\n")
print("Determinan dari matriks A adalah:", int(determinan.round()))
B= np.array ([[3,4], [2,1]])
determinan_B = np.linalg.det(B)
print (B, "\n")
print("Determinan dari matriks B adalah:", int(determinan_B.round()))
C = np.array ([[4,1], [2,1]])
determinan_C = np.linalg.det(C)
print (C, "\n")
print("Determinan dari matriks C adalah:", int(determinan_C.round()))

[[7 5]
 [2 1]] 

Determinan dari matriks A adalah: -3
[[3 4]
 [2 1]] 

Determinan dari matriks B adalah: -5
[[4 1]
 [2 1]] 

Determinan dari matriks C adalah: 2


### 7.  Mengalikan setiap entri di kolom pertama dengan kofaktor yang sesuai, dan kemudian menjumlahkan hasilnya

In [ ]:
import numpy as np
A = np.array ([[1,3,2], [0,2,2], [0,0,1]])
determinan = np.linalg.det(A)
print (A, "\n")
print("Determinan matriks adalah:", int(determinan))

[[1 3 2]
 [0 2 2]
 [0 0 1]] 

Determinan matriks adalah: 2


In [ ]:
import numpy as np
A = np.array ([[2,1,5], [0,4,1], [0,0,2]])
determinan = np.linalg.det(A)
print (A, "\n")
print("Determinan matriks adalah:", int(determinan))

[[2 1 5]
 [0 4 1]
 [0 0 2]] 

Determinan matriks adalah: 15


## Menghitung determinan matriks (ordo 5x5) dan mencari invers matriks dengan menggunakan rumus (invers matriks = join matriks A / determinan matriks A)

In [6]:
import numpy as np

# Matriks yang diberikan
matriks = np.array([[3, 1, 3, 1, 2],
                    [2, 1, 3, 1, 3],
                    [3, 2, 4, 1, 2],
                    [1, 3, 1, 2, 4],
                    [3, 2, 2, 1, 4]])

# Menghitung invers matriks
invers_matriks = np.linalg.inv(matriks)

print("Invers matriks:")
print(invers_matriks.round())

Invers matriks:
[[ 1. -1. -0. -0.  0.]
 [-1. -0.  1.  0.  0.]
 [-0.  0.  0. -0. -0.]
 [ 2. -0. -1.  1. -1.]
 [-0.  0. -0. -0.  0.]]


In [14]:
import numpy as np

def determinan_submatrix(matriks, i, j):
    # Menghapus baris i dan kolom j untuk mendapatkan submatriks
    submatriks = np.delete(np.delete(matriks, i, axis=0), j, axis=1)
    # Menghitung determinan dari submatriks
    return np.linalg.det(submatriks)

def hitung_c_ij(matriks, i, j):
    # Menghitung determinan dari submatriks dan mengalikannya dengan (-1)^(i+j)
    determinan = (-1) ** (i + j) * determinan_submatrix(matriks, i, j)
    return determinan

# Matriks yang diberikan
matriks = np.array([[3, 1, 3, 1, 2],
                    [2, 1, 3, 1, 3],
                    [3, 2, 4, 1, 2],
                    [1, 3, 1, 2, 4],
                    [3, 2, 2, 1, 4]])
print ('Join matriks')
# Menghitung c_ij untuk semua elemen dari baris 1 hingga 5 dan kolom 1 hingga 5
for i in range(len(matriks)):
    for j in range(len(matriks[i])):
        hasil = hitung_c_ij(matriks, i, j)
        print(f"baris {j+1} kolom {i+1}: {hasil}")

Join matriks
baris 1 kolom 1: -14.000000000000004
baris 2 kolom 1: 14.000000000000004
baris 3 kolom 1: 8.000000000000002
baris 4 kolom 1: -34.00000000000001
baris 5 kolom 1: 8.000000000000002
baris 1 kolom 2: 12.0
baris 2 kolom 2: 10.000000000000002
baris 3 kolom 2: -10.000000000000002
baris 4 kolom 2: 4.000000000000001
baris 5 kolom 2: -10.000000000000002
baris 1 kolom 3: 4.000000000000001
baris 2 kolom 3: -15.000000000000007
baris 3 kolom 3: -7.000000000000001
baris 4 kolom 3: 16.000000000000007
baris 5 kolom 3: 4.000000000000001
baris 1 kolom 4: 2.0
baris 2 kolom 4: -2.0000000000000013
baris 3 kolom 4: 2.0000000000000004
baris 4 kolom 4: -13.999999999999996
baris 5 kolom 4: 2.0
baris 1 kolom 5: -6.000000000000001
baris 2 kolom 5: -5.000000000000001
baris 3 kolom 5: 5.000000000000001
baris 4 kolom 5: 20.000000000000007
baris 5 kolom 5: -6.000000000000003


In [8]:
import numpy as np

# Matriks yang diberikan

matriks = np.array([[3, 1, 3, 1, 2],
                    [2, 1, 3, 1, 3],
                    [3, 2, 4, 1, 2],
                    [1, 3, 1, 2, 4],
                    [3, 2, 2, 1, 4]])

# Menghitung determinan matriks
determinan = np.linalg.det(matriks)

print("Determinan matriks:")
print(determinan)

Determinan matriks:
-22.000000000000004


In [13]:
import numpy as np
determinan = -22.000000000000004
# Matriks yang diberikan
join_matriks = np.array([[-14.000000000000004, 12.0, 4.000000000000001, 2.0, -6.000000000000001],
                    [14.000000000000004, 10.000000000000002, -15.000000000000007, -2.0000000000000013, -5.000000000000001],
                    [8.000000000000002,-10.000000000000002, -7.000000000000001, 2.0000000000000004, 5.000000000000001],
                    [-34.00000000000001, 4.000000000000001, 16.000000000000007, -13.999999999999996,20.000000000000007],
                    [8.000000000000002, -10.000000000000002, 4.000000000000001, 2.0, -6.000000000000003 ]])

# Menghitung iners
invers = join_matriks/determinan

print("Invers matriks:")
print(invers.round())
print('terbukti bahwa join_matriks/determinan akan menghasilkan invers matriks')


Invers matriks:
[[ 1. -1. -0. -0.  0.]
 [-1. -0.  1.  0.  0.]
 [-0.  0.  0. -0. -0.]
 [ 2. -0. -1.  1. -1.]
 [-0.  0. -0. -0.  0.]]
terbukti bahwa join_matriks/determinan akan menghasilkan invers matriks
