# Eigenvalues dan Eigenvectors
Eigenvalues adalah nilai skalar yang terkait dengan eigenvectors dalam transformasi linier.Nilai eigen menunjukkan faktor seberapa banyak eigenvector diregangkan dalam arahnya. Ini tidak melibatkan perubahan arah vektor kecuali nilai eigen negatif. Jika nilai eigen negatif, arahnya hanya terbalik

Eigenvectors untuk matriks persegi didefinisikan sebagai nilai vektor non-nol yang ketika dikalikan dengan matriks persegi memberikan kelipatan skalar dari vektor tersebut

In [ ]:
import numpy as np
mat = np.mat([[1,4],[2,3]])
print (mat)
print(' ')
evalue, evect = np.linalg.eig(mat)
print (evalue)
print(' ')
print(evect.round())

[[1 4]
 [2 3]]
 
[-1.  5.]
 
[[-1. -1.]
 [ 0. -1.]]


## (A - λI)x = 0   Ax = λx
Merupakan matriks singular (matriks yang determinannya = 0)

In [ ]:
import numpy as np

# Definisikan matriks A
A = np.array([[4, 2], [1, 3]])

# Fungsi untuk menghitung determinan matriks (A - λI)
def determinan(A, lamb):
    return np.linalg.det(A - lamb * np.identity(A.shape[0]))

# Fungsi untuk menemukan eigenvalues (nilai λ yang membuat determinan = 0)
def find_eigenvalues(A):
    # Membuat fungsi lambda untuk determinan matriks (A - λI)
    f = lambda lamb: determinan(A, lamb)
    # Mencari nilai λ yang membuat determinan matriks (A - λI) mendekati 0
    eigenvalues = []
    for lamb in np.linspace(-10, 10, 1000):  # Rentang pencarian nilai λ
        if np.isclose(f(lamb), 0, atol=1e-3):  # Toleransi mendekati 0
            eigenvalues.append(lamb)
    return np.unique(eigenvalues)  # Mengembalikan nilai λ unik

# Menghitung eigenvalues
eigenvalues = find_eigenvalues(A)
print("Eigenvalues:", eigenvalues)

# Menghitung eigenvectors untuk setiap eigenvalue
for lamb in eigenvalues:
    # (A - λI)x = 0
    eigenvector = np.linalg.null_space(A - lamb * np.identity(A.shape[0]))
    print(f"Eigenvector untuk eigenvalue {lamb}:\n", eigenvector)


Eigenvalues: []


In [1]:
import numpy as np
from numpy.linalg import eig

# Definisikan matriks A
A = np.array([[0, 2], [2, 3]])

# Hitung eigenvalues dan eigenvectors
eigenvalues, eigenvectors = eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors.round())


Eigenvalues: [-1.  4.]
Eigenvectors:
 [[-1. -0.]
 [ 0. -1.]]
