# Invers Matriks
Invers sendiri dapat diartikan sebagai lawan dari sesuatu (kebalikan). Invers matriks dilambangkan dengan A-1. Suatu matriks dapat dilakukan invers jika jumlah baris dan kolom pada matriks tersebut harus sama. Rumus matriks yaitu sebagai berikut:

Matriks ordo(2 x 2)
$$
\begin{equation*}
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
A^-1=\frac{1}{ad-bc}
\begin{bmatrix}
d&-b\\
-c&a
\end{bmatrix}
\end{equation*}
$$

Matriks ordo (3 x 3)
$$
\begin{equation*}
A=
\begin{bmatrix}
p&q&r\\
s&t&u\\
v&w&x\
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
A^-1=\frac{1}{ptx + quv + rst - vtr - wuq - xsq}
Adj A
\end{equation*}
$$

In [2]:
import numpy as np

a=np.array([[2,-3],[-2,4]])
print('Matriks A =\n', a)

Matriks A =
 [[ 2 -3]
 [-2  4]]


Terdapat contoh suatu matriks dengan ordo (2 x 2)

Yang pertama dilakukan yaitu mencari determinan dari matriks tersebut. Dengan cara:

det A = (2 x 4) - ((-2) x (-3)) = 2

Setelah ditemukan nilai determinannya, langkah selanjutnya yaitu masukkan nilai determinan pada rumus invers ordo (2 x 2)

$$
\begin{equation*}
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
A^-1=\frac{1}{ad-bc}
\begin{bmatrix}
d&-b\\
-c&a
\end{bmatrix}
\end{equation*}
$$


In [10]:
import numpy as np

a=np.array([[(1/2)*4, (1/2)*3],[(1/2)*2, (1/2)*2]])
print('Matriks A^-1 =\n', a)

Matriks A^-1 =
 [[2.  1.5]
 [1.  1. ]]


## sifat-sifat Mtriks invers


In [1]:
import numpy as np

a=np.array([[2,3,2],[4,1,-3],[-1,-2,2]])
i = np.array([[1,0,0],[0,1,0],[0,0,1]])

print('AI=\n',a@i)
print('IA=\n',i@a)
print('A=\n',a)

AI=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
IA=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
A=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]


In [2]:
import numpy as np

# Matriks identitas 3x3
I = np.identity(3)

# Contoh matriks A (misalnya)
A = np.array([[2, 0, 0],
              [0, 3, 0],
              [0, 0, 4]])

# Menghitung invers dari matriks A
A_inv = np.linalg.inv(A)

# Menghitung invers dari matriks identitas
I_inv = np.linalg.inv(I)

# Verifikasi persamaan (A⁻¹)⁻¹ = A
if np.allclose(I_inv, A):
    print("Persamaan (A⁻¹)⁻¹ = A terpenuhi.")
else:
    print("Persamaan (A⁻¹)⁻¹ = A tidak terpenuhi.")

Persamaan (A⁻¹)⁻¹ = A tidak terpenuhi.


### 1. Invers suatu matriks taksingular adalah tunggal

### 2. Jika matriks A dan B taksingular, maka:

#### a. (A^-1)^-1=A

 matriks yang memenuhi persamaan (A⁻¹)⁻¹ = A adalah matriks identitas. Matriks identitas, biasanya dilambangkan dengan I, memiliki elemen-elemen berikut:

 I =

|       | kolom 1 | kolom 2 | kolom 3 |
|-------|---------|--------|-------|
| Baris 1 |  1 |  0 | 0  |
| Baris 2 |  0  |  1  | 0 |
| Baris 3 |  0  |  0  | 1 |

Dalam hal ini, A juga harus merupakan matriks persegi (jumlah baris dan kolom yang sama) dan inversnya harus ada (yaitu, A⁻¹ harus ada). Jadi, jika kita mengambil invers dari matriks identitas, kita akan mendapatkan kembali matriks identitas itu sendiri:

        (A^-1)^-1= I

#### b.(AB)^-1=B^-1 A^-1

#### c. (A^T)^-1=(A^-1)^T

## mencari invers dngan eliminasi gaus jordan

## solusi eliminasi persamaan linier
(membuat contoh soal persamaan linier 6 variabel)