# Invers Matriks
Invers sendiri dapat diartikan sebagai lawan dari sesuatu (kebalikan). Invers matriks dilambangkan dengan A^-1. Suatu matriks dapat dilakukan invers jika jumlah baris dan kolom pada matriks tersebut harus sama. Rumus matriks yaitu sebagai berikut:

Matriks ordo(2 x 2)
$$
\begin{equation*}
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
A^-1=\frac{1}{ad-bc}
\begin{bmatrix}
d&-b\\
-c&a
\end{bmatrix}
\end{equation*}
$$

Matriks ordo (3 x 3)
$$
\begin{equation*}
A=
\begin{bmatrix}
p&q&r\\
s&t&u\\
v&w&x\
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
A^-1=\frac{1}{ptx + quv + rst - vtr - wuq - xsq}
Adj A
\end{equation*}
$$

In [ ]:
import numpy as np

a=np.array([[2,-3],[-2,4]])
print('Matriks A =\n', a)

Matriks A =
 [[ 2 -3]
 [-2  4]]


Terdapat contoh suatu matriks dengan ordo (2 x 2)

Yang pertama dilakukan yaitu mencari determinan dari matriks tersebut. Dengan cara:

det A = (2 x 4) - ((-2) x (-3)) = 2

Setelah ditemukan nilai determinannya, langkah selanjutnya yaitu masukkan nilai determinan pada rumus invers ordo (2 x 2)

$$
\begin{equation*}
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
A^-1=\frac{1}{ad-bc}
\begin{bmatrix}
d&-b\\
-c&a
\end{bmatrix}
\end{equation*}
$$


In [ ]:
import numpy as np

a=np.array([[(1/2)*4, (1/2)*3],[(1/2)*2, (1/2)*2]])
print('Matriks A^-1 =\n', a)

Matriks A^-1 =
 [[2.  1.5]
 [1.  1. ]]


## Sifat-sifat Matriks Invers
1. Invers matriks jika ada, tunggal (hanya satu).

2. Invers matriks (A) ditulis sebagai (A^{-1}).

3. Jika suatu matriks memiliki invers, maka matriks tersebut adalah matriks nonsingular.

4. Sebaliknya, jika suatu matriks tidak memiliki invers, maka matriks tersebut adalah matriks singular

5. Invers dari matriks adalah tunggal


In [ ]:
import numpy as np

a=np.array([[2,3,2],[4,1,-3],[-1,-2,2]])
i = np.array([[1,0,0],[0,1,0],[0,0,1]])

print('AI=\n',a@i)
print('IA=\n',i@a)
print('A=\n',a)

AI=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
IA=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
A=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]


## Mencari Invers Dengan Eliminasi Gauss Jordan Elimination
$$
\begin{equation*}
A=
\begin{bmatrix}
10&2\\
6&3
\end{bmatrix}
\end{equation*}
$$

Terdapat matriks A di sebelah kiri dan matriks Identitas I di sebelah kanannya dipisahkan dengan garis putus-putus

$$
\begin{equation*}
A=
\begin{bmatrix}
10&2& | &1 &0\\
6&3 &| & 0 & 1\\
\end{bmatrix}
\end{equation*}
$$

Bagilah Baris [1] dengan 10 (untuk memberi kita "1" di posisi yang diinginkan), sehingga :

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0,2& | &0,1 &0\\
6&3 &| & 0 & 1\\
\end{bmatrix}
\end{equation*}
$$

Baris[2] ( -6 ) x Baris[1] (untuk memberi angka 0 pada posisi yang diinginkan):

6 − 6 × 1 = 0

3 − 6 × 0.2 = 1.8

0 − 6 × 0.1 = -0.6

1 − 6 × 0 = 1

Sehingga diperoleh baris [2] :

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0,2& | &0,1 &0\\
0&1,8 &| & -0,6 & 1\\
\end{bmatrix}
\end{equation*}
$$

Bagilah Baris [2] dengan 1,8 (untuk memberi angka "1" di posisi yang diinginkan), sehingga :

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0,2& | &0,1 &0\\
0&1 &| & -0,3333 & 0,5556\\
\end{bmatrix}
\end{equation*}
$$

Baris [1] (- 0,2) x Baris [2] (untuk memberi angka 0 di posisi yang diinginkan):

1 − 0.2 × 0 = 1

0.2 − 0.2 × 1 = 0

0.1 − 0.2 × -0.3333 = 0.1667

0 − 0.2 × 0.5556 = -0.1111

Sehingga diperoleh baris [1] :

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0& | &0,1667 & -0,1111\\
0&1 &| & -0,3333 & 0,5556\\
\end{bmatrix}
\end{equation*}
$$

Sehingga diperoleh invers matriks A yaitu :

$$
\begin{equation*}
A^-1=
\begin{bmatrix}
0,1667 & -0,1111\\
-0,3333 & 0,5556\\
\end{bmatrix}
\end{equation*}
$$

In [ ]:
import numpy as np

def invers_matriks_2x2(A):
    # Periksa apakah matriks A dapat diinverskan
    if np.linalg.det(A) == 0:
        print("Matriks tidak dapat diinverskan karena determinan = 0.")
        return None

    # Buat matriks identitas berukuran 2x2
    I = np.eye(2)

    # Gabungkan matriks A dan matriks identitas
    aug_matrix = np.hstack((A, I))

    # Lakukan operasi baris elementer untuk mengubah matriks A menjadi matriks identitas
    for i in range(2):
        # Bagi baris ke-i dengan elemen diagonal
        pivot = aug_matrix[i, i]
        aug_matrix[i, :] /= pivot
        # Kurangi baris lain dengan kelipatan baris ke-i
        for j in range(2):
          if j != i:
            factor = aug_matrix[j, i]
            aug_matrix[j, :] -= factor * aug_matrix[i, :]

     # Matriks invers berada di sisi kanan matriks augmentasi
    invers_A = aug_matrix[:, 2:]

    return invers_A

# Contoh penggunaan
A = np.array([[10, 2], [6, 3]])
invers_A = invers_matriks_2x2(A)
print("Matriks A:")
print(A)
print("\nMatriks invers A:")
print(invers_A)




Matriks A:
[[10  2]
 [ 6  3]]

Matriks invers A:
[[ 0.16666667 -0.11111111]
 [-0.33333333  0.55555556]]


## Solusi Eliminasi Persamaan Linier
(membuat contoh soal persamaan linier 6 variabel)

$$
\\2x + y + 0z + 0w + 0u + 0v = 0\\
x + 3y + z + 0w +0 u + 0v = 0\\
0x + y + 2z + w + 0u + 0v = 0\\
0x + 0y + z + 3w + u + 0v = 0\\
0x + 0y + 0z + w + 2u + v = 0\\
0x + 0y + 0z + 0w + u + 3v = 0\\
$$

matriks augmented dari sistem persamaan ini:


$$
\begin{bmatrix}
2 & 1 & 0 & 0 & 0 & 0 & | & 0 \\
1 & 3 & 1 & 0 & 0 & 0 & | & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 \
\end{bmatrix}
$$


Menulis matriks augmented :


$$
\begin{bmatrix}
2 & 1 & 0 & 0 & 0 & 0 & | & 1 & 0 & 0 & 0 & 0 & 0 \\
1 & 3 & 1 & 0 & 0 & 0 & | & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Tukar baris ke-2 dan ke-1


$$
\begin{bmatrix}
1 & 3 & 1 & 0 & 0 & 0 & | & 0 & 1 & 0 & 0 & 0 & 0 \\
2 & 1 & 0 & 0 & 0 & 0 & | & 1 & 0 & 0 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kalikan baris ke-1 dengan 2


$$
\begin{bmatrix}
2 & 6 & 2 & 0 & 0 & 0 & | & 0 & 2 & 0 & 0 & 0 & 0 \\
2 & 1 & 0 & 0 & 0 & 0 & | & 1 & 0 & 0 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kurangi baris ke-2 dengan baris ke-1 dan kemudian baris ke-1 dibagi 2


$$
\begin{bmatrix}
1 & 3 & 1 & 0 & 0 & 0 & | & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & -5 & -2 & 0 & 0 & 0 & | & 1 & -2 & 0 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Tukar baris ke-3 dan ke-2


$$
\begin{bmatrix}
1 & 3 & 1 & 0 & 0 & 0 & | & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & -5 & -2 & 0 & 0 & 0 & | & 1 & -2 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kalikan baris ke-2 dengan 3


$$
\begin{bmatrix}
1 & 3 & 1 & 0 & 0 & 0 & | & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & 3 & 6 & 3 & 0 & 0 & | & 0 & 0 & 3 & 0 & 0 & 0 \\
0 & -5 & -2 & 0 & 0 & 0 & | & 1 & -2 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kurangi baris ke-1 dengan baris ke-2 dan bagikan baris ke-2 dengan 3


$$
\begin{bmatrix}
1 & 0 & -5 & -3 & 0 & 0 & | & 0 & 1 & -3 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & -5 & -2 & 0 & 0 & 0 & | & 1 & -2 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kalikan baris ke-2 dengan -5


$$
\begin{bmatrix}
1 & 0 & -5 & -3 & 0 & 0 & | & 0 & 1 & -3 & 0 & 0 & 0 \\
0 & -5 & -10 & -5 & 0 & 0 & | & 0 & 0 & -5 & 0 & 0 & 0 \\
0 & -5 & -2 & 0 & 0 & 0 & | & 1 & -2 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kurangi baris ke-3 dengan baris ke-2 dan bagikan baris ke-2 dengan (-5)


$$
\begin{bmatrix}
1 & 0 & -5 & -3 & 0 & 0 & | & 0 & 1 & -3 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 8 & 5 & 0 & 0 & | & 1 & -2 & 5 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Tukar baris ke-4 dan ke-3


$$
\begin{bmatrix}
1 & 0 & -5 & -3 & 0 & 0 & | & 0 & 1 & -3 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 8 & 5 & 0 & 0 & | & 1 & -2 & 5 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kalikan baris ke-3 dengan (-5)


$$
\begin{bmatrix}
1 & 0 & -5 & -3 & 0 & 0 & | & 0 & 1 & -3 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & -5 & -15 & -5 & 0 & | & 0 & 0 & 0 & -5 & 0 & 0 \\
0 & 0 & 8 & 5 & 0 & 0 & | & 1 & -2 & 5 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kurangi baris ke-1 dengan baris ke-3 dan bagikan baris ke-3 dengan (-5)


$$
\begin{bmatrix}
1 & 0 & 0 & 12 & 5 & 0 & | & 0 & 1 & -3 & 5 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 8 & 5 & 0 & 0 & | & 1 & -2 & 5 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kalikan baris ke-3 dengan 2


$$
\begin{bmatrix}
1 & 0 & 0 & 12 & 5 & 0 & | & 0 & 1 & -3 & 5 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 2 & 6 & 2 & 0 & | & 0 & 0 & 0 & 2 & 0 & 0 \\
0 & 0 & 8 & 5 & 0 & 0 & | & 1 & -2 & 5 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kurangi baris ke-2 dengan baris ke-3 dan bagikan baris ke-3 dengan 2


$$
\begin{bmatrix}
1 & 0 & 0 & 12 & 5 & 0 & | & 0 & 1 & -3 & 5 & 0 & 0 \\
0 & 1 & 0 & -5 & -2 & 0 & | & 0 & 0 & 1 & -2 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 8 & 5 & 0 & 0 & | & 1 & -2 & 5 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kalikan baris ke-3 dengan 8

$$
\begin{bmatrix}
1 & 0 & 0 & 12 & 5 & 0 & | & 0 & 1 & -3 & 5 & 0 & 0 \\
0 & 1 & 0 & -5 & -2 & 0 & | & 0 & 0 & 1 & -2 & 0 & 0 \\
0 & 0 & 8 & 24 & 8 & 0 & | & 0 & 0 & 0 & 8 & 0 & 0 \\
0 & 0 & 8 & 5 & 0 & 0 & | & 1 & -2 & 5 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kurangi baris ke-4 dengan baris ke-3 dan bagikan baris ke-3 dengan 8

$$
\begin{bmatrix}
1 & 0 & 0 & 12 & 5 & 0 & | & 0 & 1 & -3 & 5 & 0 & 0 \\
0 & 1 & 0 & -5 & -2 & 0 & | & 0 & 0 & 1 & -2 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Tukar baris ke-5 dan ke-4

$$
\begin{bmatrix}
1 & 0 & 0 & 12 & 5 & 0 & | & 0 & 1 & -3 & 5 & 0 & 0 \\
0 & 1 & 0 & -5 & -2 & 0 & | & 0 & 0 & 1 & -2 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kalikan baris ke-4 dengan 12

$$
\begin{bmatrix}
1 & 0 & 0 & 12 & 5 & 0 & | & 0 & 1 & -3 & 5 & 0 & 0 \\
0 & 1 & 0 & -5 & -2 & 0 & | & 0 & 0 & 1 & -2 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 12 & 24 & 12 & | & 0 & 0 & 0 & 0 & 12 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kurangi baris ke-1 dengan baris ke-4 dan bagikan baris ke-4 dengan 12

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & -5 & -2 & 0 & | & 0 & 0 & 1 & -2 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kalikan baris ke-4 dengan -5

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & -5 & -2 & 0 & | & 0 & 0 & 1 & -2 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & -5 & -10 & -5 & | & 0 & 0 & 0 & 0 & -5 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kurangi baris ke-2 dengan baris ke-4 dan bagikan baris ke-4 dengan (-5)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kalikan baris ke-4 dengan 3

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 3 & 6 & 3 & | & 0 & 0 & 0 & 0 & 3 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kurangi baris ke-3 dengan baris ke-4 dan bagikan baris ke-4 dengan 3

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kalikan baris ke-4 dengan (-19)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & -19 & -38 & -19 & | & 0 & 0 & 0 & 0 & -19 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kurangi baris ke-5 dengan baris ke-4 dan bagikan baris ke-4 dengan (19)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Tukar baris ke-6 dan ke-5

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kalikan baris ke-5 dengan (-19)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & -19 & -57 & | & 0 & 0 & 0 & 0 & 0 & -19 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kurangi baris ke-1 dengan baris ke-5 dan bagikan baris ke-5 dengan (-19)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kalikan baris ke-5 dengan 8

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 8 & 24 & | & 0 & 0 & 0 & 0 & 0 & 8 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kurangi baris ke-2 dengan baris ke-5 dan bagikan baris ke-5 dengan 8

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kalikan baris ke-5 dengan (-5)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & -5 & -15 & | & 0 & 0 & 0 & 0 & 0 & -5 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kurangi baris ke-3 dengan baris ke-5 dan membagikan baris-5 dengan (-5)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kalikan baris ke-5 dengan 2

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 2 & 6 & | & 0 & 0 & 0 & 0 & 0 & 2 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kurangi baris ke-4 dengan baris ke-5 dan membagikan baris ke-5 dengan 2

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kalikan baris ke-5 dengan 30

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 30 & 90 & | & 0 & 0 & 0 & 0 & 0 & 30 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kurangi baris ke-6 dengan baris ke-5 dan membagikan baris ke-5 dengan 30

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & -71 & | & 1 & -2 & 5 & -8 & 19 & -30 \
\end{bmatrix}
$$

Membagi baris ke-6 dengan -71

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 1 & | & -1/71 & 2/71 & -5/71 & 8/71 & -19/71 & 30/71\
\end{bmatrix}
$$

Kalikan baris ke-6 dengan 45

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 45 & | & -45/71 & 90/71 & -225/71 & 360/71 & -855/71 & 1350/71\
\end{bmatrix}
$$

Kurangi baris ke-1 dengan baris ke-6 dan membagi baris ke-6 dengan 45

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 1 & | & -1/71 & 2/71 & -5/71 & 8/71 & -19/71 & 30/71\
\end{bmatrix}
$$

Kalikan baris ke-6 dengan (-19)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & -19 & | & 19/71 & -38/71 & 95/71 & -152/71 & 361/71 & -570/71\
\end{bmatrix}
$$

Kurangi baris ke-2 dengan baris ke-6 dan membagi baris ke-6 dengan (-19)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & 0 & | & -19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 1 & | & -1/71 & 2/71 & -5/71 & 8/71 & -19/71 & 30/71\
\end{bmatrix}
$$

Kalikan baris ke-6 dengan 12

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & 0 & | & -19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 12 & | & -12/71 & 24/71 & -60/71 & 96/71 & -228/71 & 360/71\
\end{bmatrix}
$$

Kurangi baris ke-3 dengan baris ke-6 dan membagikan baris ke-6 dengan 12

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & 0 & | & -19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
0 & 0 & 1 & 0 & 0 & 0 & | & 12/71 & -24/71 & 60/71 & -25/71 & 15/71 & -5/71 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 1 & | & -1/71 & 2/71 & -5/71 & 8/71 & -19/71 & 30/71\
\end{bmatrix}
$$

Kalikan baris ke-6 dengan -5

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & 0 & | & -19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
0 & 0 & 1 & 0 & 0 & 0 & | & 12/71 & -24/71 & 60/71 & -25/71 & 15/71 & -5/71 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & -5 & | & 5/71 & -10/71 & 25/71 & -40/71 & 95/71 &-150/71\
\end{bmatrix}
$$

Kurangi baris ke-4 dengan baris ke-6 dan membagi baris ke-6 dengan (-5)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & 0 & | & -19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
0 & 0 & 1 & 0 & 0 & 0 & | & 12/71 & -24/71 & 60/71 & -25/71 & 15/71 & -5/71 \\
0 & 0 & 0 & 1 & 0 & 0 & | & -5/71 & 10/71 & -25/71 & 40/71 & -24/71 & 8/71 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 1 & | & -1/71 & 2/71 & -5/71 & 8/71 & -19/71 & 30/71\
\end{bmatrix}
$$

Kalikan baris ke-6 dengan 3

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & 0 & | & -19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
0 & 0 & 1 & 0 & 0 & 0 & | & 12/71 & -24/71 & 60/71 & -25/71 & 15/71 & -5/71 \\
0 & 0 & 0 & 1 & 0 & 0 & | & -5/71 & 10/71 & -25/71 & 40/71 & -24/71 & 8/71 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 3 & | & -3/71 & 6/71 & -15/71 & 24/71 & -57/71 & 90/71\
\end{bmatrix}
$$

Kurangi baris ke-5 dengan baris ke-6 dan membagi baris ke-6 dengan 3

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & 0 & | & -19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
0 & 0 & 1 & 0 & 0 & 0 & | & 12/71 & -24/71 & 60/71 & -25/71 & 15/71 & -5/71 \\
0 & 0 & 0 & 1 & 0 & 0 & | & -5/71 & 10/71 & -25/71 & 40/71 & -24/71 & 8/71 \\
0 & 0 & 0 & 0 & 1 & 0 & | & 3/71 & -6/71 & 15/71 & -24/71 & 57/71 & -19/71 \\
0 & 0 & 0 & 0 & 0 & 1 & | & -1/71 & 2/71 & -5/71 & 8/71 & -19/71 & 30/71\
\end{bmatrix}
$$

Sehingga invers matriks yang dihasilkan yaitu

$$
\begin{bmatrix}
45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
-19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
12/71 & -24/71 & 60/71 & -25/71 & 15/71 & -5/71 \\
-5/71 & 10/71 & -25/71 & 40/71 & -24/71 & 8/71 \\
3/71 & -6/71 & 15/71 & -24/71 & 57/71 & -19/71 \\
-1/71 & 2/71 & -5/71 & 8/71 & -19/71 & 30/71\
\end{bmatrix}
$$



####Menentukan matriks invers dengan ordo 6x6 mengguanakan code program

In [ ]:
import numpy as np
import sys

# Koefisien matriks 6x6 (ganti dengan koefisien matriks yang sesuai)
a = np.array([[2,1,0,0,0,0], [1,3,1,0,0,0], [0,1,2,1,0,0], [0,0,1,3,1,0], [0,0,0,1,2,1], [0,0,0,0,1,3]])

# Augmentasi dengan matriks identitas 6x6
n = a.shape[0]
identity_matrix = np.identity(n)
augmented_matrix = np.hstack((a, identity_matrix))

# Terapkan Eliminasi Gauss-Jordan
for i in range(n):
    if augmented_matrix[i][i] == 0.0:
        sys.exit('Pembagian dengan nol terdeteksi!')
    for j in range(n):
        if i != j:
            ratio = augmented_matrix[j][i] / augmented_matrix[i][i]
            for k in range(2 * n):
                augmented_matrix[j][k] = augmented_matrix[j][k] - ratio * augmented_matrix[i][k]

# Operasi baris untuk membuat elemen diagonal utama menjadi 1
for i in range(n):
    divisor = augmented_matrix[i][i]
    for j in range(2 * n):
        augmented_matrix[i][j] = augmented_matrix[i][j] / divisor

# Matriks invers
inverse_matrix = augmented_matrix[:, n:]

# Tampilkan matriks invers
print('\nMATRIKS INVERS ADALAH:')
for i in range(n):
    for j in range(n):
        print(inverse_matrix[i][j], end='\t')
    print()


MATRIKS INVERS ADALAH:
0.6338028169014084	-0.2676056338028169	0.16901408450704225	-0.07042253521126761	0.04225352112676056	-0.014084507042253521	
-0.26760563380281693	0.5352112676056339	-0.3380281690140845	0.1408450704225352	-0.08450704225352113	0.02816901408450704	
0.16901408450704222	-0.33802816901408445	0.8450704225352113	-0.352112676056338	0.2112676056338028	-0.07042253521126761	
-0.07042253521126761	0.14084507042253522	-0.352112676056338	0.5633802816901409	-0.3380281690140845	0.11267605633802816	
0.042253521126760556	-0.08450704225352111	0.21126760563380279	-0.33802816901408445	0.8028169014084507	-0.2676056338028169	
-0.014084507042253521	0.028169014084507043	-0.0704225352112676	0.11267605633802817	-0.2676056338028169	0.4225352112676056	


####Menentukan nilai dari x, y, z, w, u, v menggunakan code program

In [ ]:
import numpy as np

# Matriks koefisien
A = np.array([[45/71, -19/71, 12/71, -5/71, 3/71, -1/71],
              [-19/71, 38/71, -24/71, 10/71, -6/71, 2/71],
              [12/71, -24/71, 60/71, -25/71, 15/71, -5/71],
              [-5/71, 10/71, -25/71, 40/71, -24/71, 8/71],
              [3/71, -6/71, 15/71, -24/71, 57/71, -19/71],
              [-1/71, 2/71, -5/71, 8/71, -19/71, 30/71]])


# Vektor hasil
B = np.array([0, 0, 0, 0, 0, 0])

# Menggunakan metode eliminasi Gauss-Jordan
n = len(B)
for i in range(n):
    # Skala baris ke-i sehingga elemen utama menjadi 1
    A[i] = A[i] / A[i, i]
    B[i] = B[i] / A[i, i]
    for j in range(n):
        if i != j:
            A[j] -= A[j, i] * A[i]
            B[j] -= A[j, i] * B[i]

# Solusi SPL
x1, x2, x3, x4, x5, x6 = B
print(f"Nilai variabelnya adalah:")
print(f"x = ", x1)
print(f"y = ", x2)
print(f"z = ", x3)
print(f"w = ", x4)
print(f"u = ", x5)
print(f"v = ", x6)

Nilai variabelnya adalah:
x =  0
y =  0
z =  0
w =  0
u =  0
v =  0


####Membuktikan bahwa "Jika matriks A dikalikan dengan invers matriks A akan menghasilkan matriks identitas"

In [5]:
import numpy as np

# Matriks koefisien persamaan
Invers_Matriks_A = np.array([[45/71, -19/71, 12/71, -5/71, 3/71, -1/71],
              [-19/71, 38/71, -24/71, 10/71, -6/71, 2/71],
              [12/71, -24/71, 60/71, -25/71, 15/71, -5/71],
              [-5/71, 10/71, -25/71, 40/71, -24/71, 8/71],
              [3/71, -6/71, 15/71, -24/71, 57/71, -19/71],
              [-1/71, 2/71, -5/71, 8/71, -19/71, 30/71]])

# Matriks hasil persamaan
Matriks_A = np.array([[2,1,0,0,0,0], [1,3,1,0,0,0], [0,1,2,1,0,0], [0,0,1,3,1,0], [0,0,0,1,2,1], [0,0,0,0,1,3]])

# Mengalikan matriks A dengan matriks invers matriks A
result = np.dot(Invers_Matriks_A, Matriks_A)

# Memperoleh hasil yang dibulatkan
Hasil = np.round(result)
Hasil[Hasil < 0] = 0
Hasil[Hasil != 1] = 0

# Menampilkan hasil
print("Hasil:")
print(Hasil)
print ('Terbukti bahwa matriks A dikalikan dengan invers matriks A akan menghasilkan matriks identitas')

Hasil:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Terbukti bahwa matriks A dikalikan dengan invers matriks A akan menghasilkan matriks identitas
