# Invers Matriks
Invers sendiri dapat diartikan sebagai lawan dari sesuatu (kebalikan). Invers matriks dilambangkan dengan A^-1. Suatu matriks dapat dilakukan invers jika jumlah baris dan kolom pada matriks tersebut harus sama. Rumus matriks yaitu sebagai berikut:

Matriks ordo(2 x 2)
$$
\begin{equation*}
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
A^-1=\frac{1}{ad-bc}
\begin{bmatrix}
d&-b\\
-c&a
\end{bmatrix}
\end{equation*}
$$

Matriks ordo (3 x 3)
$$
\begin{equation*}
A=
\begin{bmatrix}
p&q&r\\
s&t&u\\
v&w&x\
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
A^-1=\frac{1}{ptx + quv + rst - vtr - wuq - xsq}
Adj A
\end{equation*}
$$

In [ ]:
import numpy as np

a=np.array([[2,-3],[-2,4]])
print('Matriks A =\n', a)

Matriks A =
 [[ 2 -3]
 [-2  4]]


Terdapat contoh suatu matriks dengan ordo (2 x 2)

Yang pertama dilakukan yaitu mencari determinan dari matriks tersebut. Dengan cara:

det A = (2 x 4) - ((-2) x (-3)) = 2

Setelah ditemukan nilai determinannya, langkah selanjutnya yaitu masukkan nilai determinan pada rumus invers ordo (2 x 2)

$$
\begin{equation*}
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
A^-1=\frac{1}{ad-bc}
\begin{bmatrix}
d&-b\\
-c&a
\end{bmatrix}
\end{equation*}
$$


In [ ]:
import numpy as np

a=np.array([[(1/2)*4, (1/2)*3],[(1/2)*2, (1/2)*2]])
print('Matriks A^-1 =\n', a)

Matriks A^-1 =
 [[2.  1.5]
 [1.  1. ]]


## Sifat-sifat Matriks Invers
1. Invers matriks jika ada, tunggal (hanya satu).

2. Invers matriks (A) ditulis sebagai (A^{-1}).

3. Jika suatu matriks memiliki invers, maka matriks tersebut adalah matriks nonsingular.

4. Sebaliknya, jika suatu matriks tidak memiliki invers, maka matriks tersebut adalah matriks singular

5. Invers dari matriks adalah tunggal


In [ ]:
import numpy as np

a=np.array([[2,3,2],[4,1,-3],[-1,-2,2]])
i = np.array([[1,0,0],[0,1,0],[0,0,1]])

print('AI=\n',a@i)
print('IA=\n',i@a)
print('A=\n',a)

AI=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
IA=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
A=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]


## Mencari Invers Dengan Eliminasi Gauss Jordan Elimination
$$
\begin{equation*}
A=
\begin{bmatrix}
10&2\\
6&3
\end{bmatrix}
\end{equation*}
$$

Terdapat matriks A di sebelah kiri dan matriks Identitas I di sebelah kanannya dipisahkan dengan garis putus-putus

$$
\begin{equation*}
A=
\begin{bmatrix}
10&2& | &1 &0\\
6&3 &| & 0 & 1\\
\end{bmatrix}
\end{equation*}
$$

Bagilah Baris [1] dengan 10 (untuk memberi kita "1" di posisi yang diinginkan), sehingga :

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0,2& | &0,1 &0\\
6&3 &| & 0 & 1\\
\end{bmatrix}
\end{equation*}
$$

Baris[2] ( -6 ) x Baris[1] (untuk memberi angka 0 pada posisi yang diinginkan):

6 − 6 × 1 = 0

3 − 6 × 0.2 = 1.8

0 − 6 × 0.1 = -0.6

1 − 6 × 0 = 1

Sehingga diperoleh baris [2] :

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0,2& | &0,1 &0\\
0&1,8 &| & -0,6 & 1\\
\end{bmatrix}
\end{equation*}
$$

Bagilah Baris [2] dengan 1,8 (untuk memberi angka "1" di posisi yang diinginkan), sehingga :

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0,2& | &0,1 &0\\
0&1 &| & -0,3333 & 0,5556\\
\end{bmatrix}
\end{equation*}
$$

Baris [1] (- 0,2) x Baris [2] (untuk memberi angka 0 di posisi yang diinginkan):

1 − 0.2 × 0 = 1

0.2 − 0.2 × 1 = 0

0.1 − 0.2 × -0.3333 = 0.1667

0 − 0.2 × 0.5556 = -0.1111

Sehingga diperoleh baris [1] :

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0& | &0,1667 & -0,1111\\
0&1 &| & -0,3333 & 0,5556\\
\end{bmatrix}
\end{equation*}
$$

Sehingga diperoleh invers matriks A yaitu :

$$
\begin{equation*}
A^-1=
\begin{bmatrix}
0,1667 & -0,1111\\
-0,3333 & 0,5556\\
\end{bmatrix}
\end{equation*}
$$

In [10]:
import numpy as np
import sys

# Baca ordo matriks
n = int(input('Masukkan ordo matriks: '))

# Buat array numpy berukuran n x 2n dan inisialisasi dengan nol
a = np.zeros((n, 2 * n))

# Baca koefisien matriks
print('Masukkan koefisien matriks:')
for i in range(1, n + 1):  # Mulai dari indeks 1
    for j in range(1, n + 1):  # Mulai dari indeks 1
        a[i - 1][j - 1] = float(input(f'a[{i}][{j}]='))

# Augmentasi dengan matriks identitas berordo n
for i in range(n):
    for j in range(n):
        if i == j:
            a[i][j + n] = 1

# Terapkan Eliminasi Gauss-Jordan
for i in range(n):
    if a[i][i] == 0.0:
        sys.exit('Pembagian dengan nol terdeteksi!')
    for j in range(n):
        if i != j:
            ratio = a[j][i] / a[i][i]
            for k in range(2 * n):
                a[j][k] = a[j][k] - ratio * a[i][k]

# Operasi baris untuk membuat elemen diagonal utama menjadi 1
for i in range(n):
    divisor = a[i][i]
    for j in range(2 * n):
        a[i][j] = a[i][j] / divisor

# Tampilkan matriks invers
print('\nMATRIKS INVERS ADALAH:')
for i in range(n):
    for j in range(n, 2 * n):
        print(a[i][j], end='\t')
    print()

Masukkan ordo matriks: 2
Masukkan koefisien matriks:
a[1][1]=10
a[1][2]=2
a[2][1]=6
a[2][2]=3

MATRIKS INVERS ADALAH:
0.16666666666666666	-0.11111111111111112	
-0.3333333333333333	0.5555555555555556	


## Solusi Eliminasi Persamaan Linier
(membuat contoh soal persamaan linier 6 variabel)

$$
\\3x + 2y - 4z + 5w - 2u + v = 10\\
-x + 4y + 2z - 3w + u - 2v = 5\\
2x - y + 3z - 4w + 2u + v = 15\\
x + 2y - z + w - u + 2v = 8\\
-2x + 3y + 4z - 5w + u - v = 12\\
4x - y - 2z + 3w - 2u + v = 20\\
$$

matriks augmented dari sistem persamaan ini:


$$
\begin{bmatrix}
2 & 3 & -4 & 5 & -2 & 1 & | & 10 \\
-1 & 4 & 2 & -3 & 1 & -2 & | & 5 \\
2 & -1 & 3 & -4 & 2 & 1 & | & 15 \\
5 & 2 & -1 & 1 & -1 & 2 & | & 8 \\
-2 & 3 & 4 & -5 & 1 & -1 & | & 12 \\
4 & -1 & -2 & 3 & -2 & 1 & | & 20 \
\end{bmatrix}
$$


Menulis matriks augmented :


$$
\begin{bmatrix}
2 & 3 & -4 & 5 & -2 & 1 & | & 1 & 0 & 0 & 0 & 0 & 0 \\
-1 & 4 & 2 & -3 & 1 & -2 & | & 0 & 1 & 0 & 0 & 0 & 0 \\
2 & -1 & 3 & -4 & 2 & 1 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
5 & 2 & -1 & 1 & -1 & 2 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
-2 & 3 & 4 & -5 & 1 & -1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
4 & -1 & -2 & 3 & -2 & 1 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Temukan di kolom ke-1 (membalikkan tanda di seluruh baris) dan tukar baris ke-2 dan ke-1


$$
\begin{bmatrix}
1 & -4 & -2 & 3 & -1 & 2 & | & 0 & -1 & 0 & 0 & 0 & 0 \\
2 & 3 & -4 & 5 & -2 & 1 & | & 1 & 0 & 0 & 0 & 0 & 0 \\
2 & -1 & 3 & -4 & 2 & 1 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
5 & 2 & -1 & 1 & -1 & 2 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
-2 & 3 & 4 & -5 & 1 & -1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
4 & -1 & -2 & 3 & -2 & 1 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Hilangkan kolom ke-1


$$
\begin{bmatrix}
1 & -4 & -2 & 3 & -1 & 2 & | & 0 & -1 & 0 & 0 & 0 & 0 \\
0 & 11 & 0 & -1 & 0 & -3 & | & 1 & 2 & 0 & 0 & 0 & 0 \\
0 & 7 & 7 & -10 & 4 & -3 & | & 0 & 2 & 1 & 0 & 0 & 0 \\
0 & 22 & 9 & -14 & 4 & -8 & | & 0 & 5 & 0 & 1 & 0 & 0 \\
0 & -5 & 0 & 1 & -1 & 3 & | & 0 & -2 & 0 & 0 & 1 & 0 \\
0 & 15 & 6 & -9 & 2 & -7 & | & 0 & 4 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Pada kolom ke-2 dengan membagi baris ke-2 dengan 11


$$
\begin{bmatrix}
1 & -4 & -2 & 3 & -1 & 2 & | & 0 & -1 & 0 & 0 & 0 & 0 \\
0 & 1 & 0 & -1/11 & 0 & -3/11 & | & 1/11 & 2/11 & 0 & 0 & 0 & 0 \\
0 & 7 & 7 & -10 & 4 & -3 & | & 0 & 2 & 1 & 0 & 0 & 0 \\
0 & 22 & 9 & -14 & 4 & -8 & | & 0 & 5 & 0 & 1 & 0 & 0 \\
0 & -5 & 0 & 1 & -1 & 3 & | & 0 & -2 & 0 & 0 & 1 & 0 \\
0 & 15 & 6 & -9 & 2 & -7 & | & 0 & 4 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Hilangkan kolom ke-1


$$
\begin{bmatrix}
1 & 0 & -2 & 29/11 & -1 & 10/11 & | & 4/11 & -3/11 & 0 & 0 & 0 & 0 \\
0 & 1 & 0 & -1/11 & 0 & -3/11 & | & 1/11 & 2/11 & 0 & 0 & 0 & 0 \\
0 & 0 & 7 & -103/11 & 4 & -12/11 & | & -7/11 & 8/11 & 1 & 0 & 0 & 0 \\
0 & 0 & 9 & -12 & 4 & -2 & | & -2 & 1 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 6/11 & -1 & 18/11 & | & 5/11 & -12/11 & 0 & 0 & 1 & 0 \\
0 & 0 & 6 & -84/11 & 2 & -32/11 & | & -15/11 & 14/11 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Pada kolom ke-3 membagi baris ke-3 dengan 7


$$
\begin{bmatrix}
1 & 0 & -2 & 29/11 & -1 & 10/11 & | & 4/11 & -3/11 & 0 & 0 & 0 & 0 \\
0 & 1 & 0 & -1/11 & 0 & -3/11 & | & 1/11 & 2/11 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & -103/77 & 4/7 & -12/77 & | & -1/11 & 8/77 & 1/7 & 0 & 0 & 0 \\
0 & 0 & 9 & -12 & 4 & -2 & | & -2 & 1 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 6/11 & -1 & 18/11 & | & 5/11 & -12/11 & 0 & 0 & 1 & 0 \\
0 & 0 & 6 & -84/11 & 2 & -32/11 & | & -15/11 & 14/11 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Hilangkan kolom ke-3


$$
\begin{bmatrix}
1 & 0 & 0 & -3/77 & 1/7 & 46/77 & | & 2/11 & -5/77 & 2/7 & 0 & 0 & 0 \\
0 & 1 & 0 & -1/11 & 0 & -3/11 & | & 1/11 & 2/11 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & -103/77 & 4/7 & -12/77 & | & -1/11 & 8/77 & 1/7 & 0 & 0 & 0 \\
0 & 0 & 0 & 3/77 & -8/7 & -46/77 & | & -13/11 & 5/77 & -9/7 & 1 & 0 & 0 \\
0 & 0 & 0 & 6/11 & -1 & 18/11 & | & 5/11 & -12/11 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 30/77 & -10/7 & -152/77 & | & -9/11 & 50/77 & -6/7 & 0 & 0 & 1 \
\end{bmatrix}
$$


Pada kolom ke-4 membagi baris ke-4 dengan 3/77


$$
\begin{bmatrix}
1 & 0 & 0 & -3/77 & 1/7 & 46/77 & | & 2/11 & -5/77 & 2/7 & 0 & 0 & 0 \\
0 & 1 & 0 & -1/11 & 0 & -3/11 & | & 1/11 & 2/11 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & -103/77 & 4/7 & -12/77 & | & -1/11 & 8/77 & 1/7 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & -88/3 & -46/3 & | & -91/3 & 5/3 & -33 & 77/3 & 0 & 0 \\
0 & 0 & 0 & 6/11 & -1 & 18/11 & | & 5/11 & -12/11 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 30/77 & -10/7 & -152/77 & | & -9/11 & 50/77 & -6/7 & 0 & 0 & 1 \
\end{bmatrix}
$$


Hilangkan kolom ke-4


$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -1 & 0 & | & -1 & 0 & -1 & 1 & 0 & 0 \\
0 & 1 & 0 & 0 & -8/3 & -5/3 & | & -8/3 & 1/3 & -3 & 7/3 & 0 & 0 \\
0 & 0 & 1 & 0 & -116/3 & -62/3 & | & -122/3 & 7/3 & -44 & 103/3 & 0 & 0 \\
0 & 0 & 0 & 1 & -88/3 & -46/3 & | & -91/3 & 5/3 & -33 & 77/3 & 0 & 0 \\
0 & 0 & 0 & 0 & 15 & 10 & | & 17 & -2 & 18 & -14 & 1 & 0 \\
0 & 0 & 0 & 0 & 10 & 4 & | & 11 & 0 & 12 & -10 & 0 & 1 \
\end{bmatrix}
$$


Pada kolom ke-5 membagi baris ke-5 dengan 15


$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -1 & 0 & | & -1 & 0 & -1 & 1 & 0 & 0 \\
0 & 1 & 0 & 0 & -8/3 & -5/3 & | & -8/3 & 1/3 & -3 & 7/3 & 0 & 0 \\
0 & 0 & 1 & 0 & -116/3 & -62/3 & | & -122/3 & 7/3 & -44 & 103/3 & 0 & 0 \\
0 & 0 & 0 & 1 & -88/3 & -46/3 & | & -91/3 & 5/3 & -33 & 77/3 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 2/3 & | & 17/15 & -2/15 & 6/5 & -14/15 & 1/15 & 0 \\
0 & 0 & 0 & 0 & 10 & 4 & | & 11 & 0 & 12 & -10 & 0 & 1 \
\end{bmatrix}
$$


Hilangkan kolom ke-5


$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 2/3 & | & 2/15 & -2/15 & 1/5 & 1/15 & 1/15 & 0 \\
0 & 1 & 0 & 0 & 0 & 1/9 & | & 16/45 & -1/45 & 1/5 & -7/45 & 8/45 & 0 \\
0 & 0 & 1 & 0 & 0 & 46/9 & | & 142/45 & -127/45 & 12/5 & -79/45 & 116/45 & 0 \\
0 & 0 & 0 & 1 & 0 & 38/9 & | & 131/45 & -101/45 & 11/5 & -77/45 & 88/45 & 0 \\
0 & 0 & 0 & 0 & 1 & 2/3 & | & 17/15 & -2/15 & 6/5 & -14/15 & 1/15 & 0 \\
0 & 0 & 0 & 0 & 0 & -8/3 & | & -1/3 & 4/3 & 0 & -2/3 & -2/3 & 1 \
\end{bmatrix}
$$


Pada kolom ke-6 membagi baris ke-6 dengan -8/3


$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 2/3 & | & 2/15 & -2/15 & 1/5 & 1/15 & 1/15 & 0 \\
0 & 1 & 0 & 0 & 0 & 1/9 & | & 16/45 & -1/45 & 1/5 & -7/45 & 8/45 & 0 \\
0 & 0 & 1 & 0 & 0 & 46/9 & | & 142/45 & -127/45 & 12/5 & -79/45 & 116/45 & 0 \\
0 & 0 & 0 & 1 & 0 & 38/9 & | & 131/45 & -101/45 & 11/5 & -77/45 & 88/45 & 0 \\
0 & 0 & 0 & 0 & 1 & 2/3 & | & 17/15 & -2/15 & 6/5 & -14/15 & 1/15 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & | & 1/8 & -1/2 & 0 & 1/4 & 1/4 & -3/8 \
\end{bmatrix}
$$


Hilangkan kolom ke-6


$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 1/20 & 1/5 & 1/5 & -1/10 & -1/10 & 1/4 \\
0 & 1 & 0 & 0 & 0 & 0 & | & 41/120 & 1/30 & 1/5 & -11/60 & 3/20 & 1/24 \\
0 & 0 & 1 & 0 & 0 & 0 & | & 151/60 & -4/15 & 12/5 & -91/30 & 13/10 & 23/12 \\
0 & 0 & 0 & 1 & 0 & 0 & | & 143/60 & -2/15 & 11/5 & -83/30 & 9/10 & 19/12 \\
0 & 0 & 0 & 0 & 1 & 0 & | & 21/20 & 1/5 & 6/5 & -11/10 & -1/10 & 1/4 \\
0 & 0 & 0 & 0 & 0 & 1 & | & 1/8 & -1/2 & 0 & 1/4 & 1/4 & -3/8 \
\end{bmatrix}
$$


Sehingga matriks invers yang dihasilkan yaitu :


$$
\begin{bmatrix}
1/20 & 1/5 & 1/5 & -1/10 & -1/10 & 1/4 \\
41/120 & 1/30 & 1/5 & -11/60 & 3/20 & 1/24 \\
151/60 & -4/15 & 12/5 & -91/30 & 13/10 & 23/12 \\
143/60 & -2/15 & 11/5 & -83/30 & 9/10 & 19/12 \\
21/20 & 1/5 & 6/5 & -11/10 & -1/10 & 1/4 \\
1/8 & -1/2 & 0 & 1/4 & 1/4 & -3/8 \
\end{bmatrix}
$$




In [9]:
import numpy as np
import sys

# Baca ordo matriks
n = int(input('Masukkan ordo matriks: '))

# Buat array numpy berukuran n x 2n dan inisialisasi dengan nol
a = np.zeros((n, 2 * n))

# Baca koefisien matriks
print('Masukkan koefisien matriks:')
for i in range(1, n + 1):  # Mulai dari indeks 1
    for j in range(1, n + 1):  # Mulai dari indeks 1
        a[i - 1][j - 1] = float(input(f'a[{i}][{j}]='))

# Augmentasi dengan matriks identitas berordo n
for i in range(n):
    for j in range(n):
        if i == j:
            a[i][j + n] = 1

# Terapkan Eliminasi Gauss-Jordan
for i in range(n):
    if a[i][i] == 0.0:
        sys.exit('Pembagian dengan nol terdeteksi!')
    for j in range(n):
        if i != j:
            ratio = a[j][i] / a[i][i]
            for k in range(2 * n):
                a[j][k] = a[j][k] - ratio * a[i][k]

# Operasi baris untuk membuat elemen diagonal utama menjadi 1
for i in range(n):
    divisor = a[i][i]
    for j in range(2 * n):
        a[i][j] = a[i][j] / divisor

# Tampilkan matriks invers
print('\nMATRIKS INVERS ADALAH:')
for i in range(n):
    for j in range(n, 2 * n):
        print(a[i][j], end='\t')
    print()

Masukkan ordo matriks: 6
Masukkan koefisien matriks:
a[1][1]=2
a[1][2]=3
a[1][3]=-4
a[1][4]=5
a[1][5]=-2
a[1][6]=1
a[2][1]=-1
a[2][2]=4
a[2][3]=2
a[2][4]=-3
a[2][5]=1
a[2][6]=-2
a[3][1]=2
a[3][2]=-1
a[3][3]=3
a[3][4]=-4
a[3][5]=2
a[3][6]=1
a[4][1]=5
a[4][2]=2
a[4][3]=-1
a[4][4]=1
a[4][5]=-1
a[4][6]=2
a[5][1]=-2
a[5][2]=3
a[5][3]=4
a[5][4]=-5
a[5][5]=1
a[5][6]=-1
a[6][1]=4
a[6][2]=-1
a[6][3]=-2
a[6][4]=3
a[6][5]=-2
a[6][6]=1

MATRIKS INVERS ADALAH:
0.05000000000000117	0.1999999999999999	0.20000000000000073	-0.10000000000000106	-0.09999999999999963	0.2500000000000006	
0.34166666666666656	0.033333333333333465	0.20000000000000043	-0.18333333333333376	0.15000000000000008	0.04166666666666701	
2.5166666666666786	-0.2666666666666662	2.4000000000000083	-3.033333333333349	1.3000000000000036	1.9166666666666752	
2.3833333333333386	-0.13333333333333328	2.200000000000007	-2.7666666666666773	0.9000000000000034	1.58333333333334	
1.0500000000000016	0.19999999999999984	1.2000000000000013	-1.100000000000