# Invers Matriks
Invers sendiri dapat diartikan sebagai lawan dari sesuatu (kebalikan). Invers matriks dilambangkan dengan A^-1. Suatu matriks dapat dilakukan invers jika jumlah baris dan kolom pada matriks tersebut harus sama. Rumus matriks yaitu sebagai berikut:

Matriks ordo(2 x 2)
$$
\begin{equation*}
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
A^-1=\frac{1}{ad-bc}
\begin{bmatrix}
d&-b\\
-c&a
\end{bmatrix}
\end{equation*}
$$

Matriks ordo (3 x 3)
$$
\begin{equation*}
A=
\begin{bmatrix}
p&q&r\\
s&t&u\\
v&w&x\
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
A^-1=\frac{1}{ptx + quv + rst - vtr - wuq - xsq}
Adj A
\end{equation*}
$$

In [ ]:
import numpy as np

a=np.array([[2,-3],[-2,4]])
print('Matriks A =\n', a)

Matriks A =
 [[ 2 -3]
 [-2  4]]


Terdapat contoh suatu matriks dengan ordo (2 x 2)

Yang pertama dilakukan yaitu mencari determinan dari matriks tersebut. Dengan cara:

det A = (2 x 4) - ((-2) x (-3)) = 2

Setelah ditemukan nilai determinannya, langkah selanjutnya yaitu masukkan nilai determinan pada rumus invers ordo (2 x 2)

$$
\begin{equation*}
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
A^-1=\frac{1}{ad-bc}
\begin{bmatrix}
d&-b\\
-c&a
\end{bmatrix}
\end{equation*}
$$


In [ ]:
import numpy as np

a=np.array([[(1/2)*4, (1/2)*3],[(1/2)*2, (1/2)*2]])
print('Matriks A^-1 =\n', a)

Matriks A^-1 =
 [[2.  1.5]
 [1.  1. ]]


## Sifat-sifat Matriks Invers
1. Invers matriks jika ada, tunggal (hanya satu).

2. Invers matriks (A) ditulis sebagai (A^{-1}).

3. Jika suatu matriks memiliki invers, maka matriks tersebut adalah matriks nonsingular.

4. Sebaliknya, jika suatu matriks tidak memiliki invers, maka matriks tersebut adalah matriks singular

5. Invers dari matriks adalah tunggal


In [ ]:
import numpy as np

a=np.array([[2,3,2],[4,1,-3],[-1,-2,2]])
i = np.array([[1,0,0],[0,1,0],[0,0,1]])

print('AI=\n',a@i)
print('IA=\n',i@a)
print('A=\n',a)

AI=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
IA=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
A=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]


## Mencari Invers Dengan Eliminasi Gauss Jordan Elimination
$$
\begin{equation*}
A=
\begin{bmatrix}
10&2\\
6&3
\end{bmatrix}
\end{equation*}
$$

Terdapat matriks A di sebelah kiri dan matriks Identitas I di sebelah kanannya dipisahkan dengan garis putus-putus

$$
\begin{equation*}
A=
\begin{bmatrix}
10&2& | &1 &0\\
6&3 &| & 0 & 1\\
\end{bmatrix}
\end{equation*}
$$

Bagilah Baris [1] dengan 10 (untuk memberi kita "1" di posisi yang diinginkan), sehingga :

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0,2& | &0,1 &0\\
6&3 &| & 0 & 1\\
\end{bmatrix}
\end{equation*}
$$

Baris[2] ( -6 ) x Baris[1] (untuk memberi angka 0 pada posisi yang diinginkan):

6 − 6 × 1 = 0

3 − 6 × 0.2 = 1.8

0 − 6 × 0.1 = -0.6

1 − 6 × 0 = 1

Sehingga diperoleh baris [2] :

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0,2& | &0,1 &0\\
0&1,8 &| & -0,6 & 1\\
\end{bmatrix}
\end{equation*}
$$

Bagilah Baris [2] dengan 1,8 (untuk memberi angka "1" di posisi yang diinginkan), sehingga :

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0,2& | &0,1 &0\\
0&1 &| & -0,3333 & 0,5556\\
\end{bmatrix}
\end{equation*}
$$

Baris [1] (- 0,2) x Baris [2] (untuk memberi angka 0 di posisi yang diinginkan):

1 − 0.2 × 0 = 1

0.2 − 0.2 × 1 = 0

0.1 − 0.2 × -0.3333 = 0.1667

0 − 0.2 × 0.5556 = -0.1111

Sehingga diperoleh baris [1] :

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0& | &0,1667 & -0,1111\\
0&1 &| & -0,3333 & 0,5556\\
\end{bmatrix}
\end{equation*}
$$

Sehingga diperoleh invers matriks A yaitu :

$$
\begin{equation*}
A^-1=
\begin{bmatrix}
0,1667 & -0,1111\\
-0,3333 & 0,5556\\
\end{bmatrix}
\end{equation*}
$$

In [ ]:
import numpy as np

def invers_matriks_2x2(A):
    # Periksa apakah matriks A dapat diinverskan
    if np.linalg.det(A) == 0:
        print("Matriks tidak dapat diinverskan karena determinan = 0.")
        return None

    # Buat matriks identitas berukuran 2x2
    I = np.eye(2)

    # Gabungkan matriks A dan matriks identitas
    aug_matrix = np.hstack((A, I))

    # Lakukan operasi baris elementer untuk mengubah matriks A menjadi matriks identitas
    for i in range(2):
        # Bagi baris ke-i dengan elemen diagonal
        pivot = aug_matrix[i, i]
        aug_matrix[i, :] /= pivot
        # Kurangi baris lain dengan kelipatan baris ke-i
        for j in range(2):
          if j != i:
            factor = aug_matrix[j, i]
            aug_matrix[j, :] -= factor * aug_matrix[i, :]

     # Matriks invers berada di sisi kanan matriks augmentasi
    invers_A = aug_matrix[:, 2:]

    return invers_A

# Contoh penggunaan
A = np.array([[10, 2], [6, 3]])
invers_A = invers_matriks_2x2(A)
print("Matriks A:")
print(A)
print("\nMatriks invers A:")
print(invers_A)




Matriks A:
[[10  2]
 [ 6  3]]

Matriks invers A:
[[ 0.16666667 -0.11111111]
 [-0.33333333  0.55555556]]


## Solusi Eliminasi Persamaan Linier
(membuat contoh soal persamaan linier 6 variabel)

$$
\\2x + y + 0z + 0w + 0u + 0v = 1\\
x + 3y + z + 0w +0 u + 0v = -2\\
0x + y + 2z + w + 0u + 0v = -1\\
0x + 0y + z + 3w + u + 0v = -1\\
0x + 0y + 0z + w + 2u + v = -1\\
0x + 0y + 0z + 0w + u + 3v = 2\\
$$

matriks augmented dari sistem persamaan ini:


$$
\begin{bmatrix}
2 & 1 & 0 & 0 & 0 & 0 & | & 1 \\
1 & 3 & 1 & 0 & 0 & 0 & | & -2 \\
0 & 1 & 2 & 1 & 0 & 0 & | & -1\\
0 & 0 & 1 & 3 & 1 & 0 & | & -1 \\
0 & 0 & 0 & 1 & 2 & 1 & | & -1 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 2 \
\end{bmatrix}
$$


Menulis matriks augmented :


$$
\begin{bmatrix}
2 & 1 & 0 & 0 & 0 & 0 & | & 1 & 0 & 0 & 0 & 0 & 0 \\
1 & 3 & 1 & 0 & 0 & 0 & | & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Tukar baris ke-2 dan ke-1


$$
\begin{bmatrix}
1 & 3 & 1 & 0 & 0 & 0 & | & 0 & 1 & 0 & 0 & 0 & 0 \\
2 & 1 & 0 & 0 & 0 & 0 & | & 1 & 0 & 0 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kalikan baris ke-1 dengan 2


$$
\begin{bmatrix}
2 & 6 & 2 & 0 & 0 & 0 & | & 0 & 2 & 0 & 0 & 0 & 0 \\
2 & 1 & 0 & 0 & 0 & 0 & | & 1 & 0 & 0 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kurangi baris ke-2 dengan baris ke-1 dan kemudian baris ke-1 dibagi 2


$$
\begin{bmatrix}
1 & 3 & 1 & 0 & 0 & 0 & | & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & -5 & -2 & 0 & 0 & 0 & | & 1 & -2 & 0 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Tukar baris ke-3 dan ke-2


$$
\begin{bmatrix}
1 & 3 & 1 & 0 & 0 & 0 & | & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & -5 & -2 & 0 & 0 & 0 & | & 1 & -2 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kalikan baris ke-2 dengan 3


$$
\begin{bmatrix}
1 & 3 & 1 & 0 & 0 & 0 & | & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & 3 & 6 & 3 & 0 & 0 & | & 0 & 0 & 3 & 0 & 0 & 0 \\
0 & -5 & -2 & 0 & 0 & 0 & | & 1 & -2 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kurangi baris ke-1 dengan baris ke-2 dan bagikan baris ke-2 dengan 3


$$
\begin{bmatrix}
1 & 0 & -5 & -3 & 0 & 0 & | & 0 & 1 & -3 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & -5 & -2 & 0 & 0 & 0 & | & 1 & -2 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kalikan baris ke-2 dengan -5


$$
\begin{bmatrix}
1 & 0 & -5 & -3 & 0 & 0 & | & 0 & 1 & -3 & 0 & 0 & 0 \\
0 & -5 & -10 & -5 & 0 & 0 & | & 0 & 0 & -5 & 0 & 0 & 0 \\
0 & -5 & -2 & 0 & 0 & 0 & | & 1 & -2 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kurangi baris ke-3 dengan baris ke-2 dan bagikan baris ke-2 dengan (-5)


$$
\begin{bmatrix}
1 & 0 & -5 & -3 & 0 & 0 & | & 0 & 1 & -3 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 8 & 5 & 0 & 0 & | & 1 & -2 & 5 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Tukar baris ke-4 dan ke-3


$$
\begin{bmatrix}
1 & 0 & -5 & -3 & 0 & 0 & | & 0 & 1 & -3 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 8 & 5 & 0 & 0 & | & 1 & -2 & 5 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kalikan baris ke-3 dengan (-5)


$$
\begin{bmatrix}
1 & 0 & -5 & -3 & 0 & 0 & | & 0 & 1 & -3 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & -5 & -15 & -5 & 0 & | & 0 & 0 & 0 & -5 & 0 & 0 \\
0 & 0 & 8 & 5 & 0 & 0 & | & 1 & -2 & 5 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kurangi baris ke-1 dengan baris ke-3 dan bagikan baris ke-3 dengan (-5)


$$
\begin{bmatrix}
1 & 0 & 0 & 12 & 5 & 0 & | & 0 & 1 & -3 & 5 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 8 & 5 & 0 & 0 & | & 1 & -2 & 5 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kalikan baris ke-3 dengan 2


$$
\begin{bmatrix}
1 & 0 & 0 & 12 & 5 & 0 & | & 0 & 1 & -3 & 5 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 2 & 6 & 2 & 0 & | & 0 & 0 & 0 & 2 & 0 & 0 \\
0 & 0 & 8 & 5 & 0 & 0 & | & 1 & -2 & 5 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$


Kurangi baris ke-2 dengan baris ke-3 dan bagikan baris ke-3 dengan 2


$$
\begin{bmatrix}
1 & 0 & 0 & 12 & 5 & 0 & | & 0 & 1 & -3 & 5 & 0 & 0 \\
0 & 1 & 0 & -5 & -2 & 0 & | & 0 & 0 & 1 & -2 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 8 & 5 & 0 & 0 & | & 1 & -2 & 5 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kalikan baris ke-3 dengan 8

$$
\begin{bmatrix}
1 & 0 & 0 & 12 & 5 & 0 & | & 0 & 1 & -3 & 5 & 0 & 0 \\
0 & 1 & 0 & -5 & -2 & 0 & | & 0 & 0 & 1 & -2 & 0 & 0 \\
0 & 0 & 8 & 24 & 8 & 0 & | & 0 & 0 & 0 & 8 & 0 & 0 \\
0 & 0 & 8 & 5 & 0 & 0 & | & 1 & -2 & 5 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kurangi baris ke-4 dengan baris ke-3 dan bagikan baris ke-3 dengan 8

$$
\begin{bmatrix}
1 & 0 & 0 & 12 & 5 & 0 & | & 0 & 1 & -3 & 5 & 0 & 0 \\
0 & 1 & 0 & -5 & -2 & 0 & | & 0 & 0 & 1 & -2 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Tukar baris ke-5 dan ke-4

$$
\begin{bmatrix}
1 & 0 & 0 & 12 & 5 & 0 & | & 0 & 1 & -3 & 5 & 0 & 0 \\
0 & 1 & 0 & -5 & -2 & 0 & | & 0 & 0 & 1 & -2 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kalikan baris ke-4 dengan 12

$$
\begin{bmatrix}
1 & 0 & 0 & 12 & 5 & 0 & | & 0 & 1 & -3 & 5 & 0 & 0 \\
0 & 1 & 0 & -5 & -2 & 0 & | & 0 & 0 & 1 & -2 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 12 & 24 & 12 & | & 0 & 0 & 0 & 0 & 12 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kurangi baris ke-1 dengan baris ke-4 dan bagikan baris ke-4 dengan 12

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & -5 & -2 & 0 & | & 0 & 0 & 1 & -2 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kalikan baris ke-4 dengan -5

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & -5 & -2 & 0 & | & 0 & 0 & 1 & -2 & 0 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & -5 & -10 & -5 & | & 0 & 0 & 0 & 0 & -5 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kurangi baris ke-2 dengan baris ke-4 dan bagikan baris ke-4 dengan (-5)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kalikan baris ke-4 dengan 3

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 3 & 1 & 0 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 3 & 6 & 3 & | & 0 & 0 & 0 & 0 & 3 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kurangi baris ke-3 dengan baris ke-4 dan bagikan baris ke-4 dengan 3

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kalikan baris ke-4 dengan (-19)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & -19 & -38 & -19 & | & 0 & 0 & 0 & 0 & -19 & 0 \\
0 & 0 & 0 & -19 & -8 & 0 & | & 1 & -2 & 5 & -8 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Kurangi baris ke-5 dengan baris ke-4 dan bagikan baris ke-4 dengan (-19)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Tukar baris ke-6 dan ke-5

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kalikan baris ke-5 dengan (-19)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -19 & -12 & | & 0 & 1 & -3 & 5 & -12 & 0 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & -19 & -57 & | & 0 & 0 & 0 & 0 & 0 & -19 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kurangi baris ke-1 dengan baris ke-5 dan bagikan baris ke-5 dengan (-19)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kalikan baris ke-5 dengan 8

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 8 & 5 & | & 0 & 0 & 1 & -2 & 5 & 0 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 8 & 24 & | & 0 & 0 & 0 & 0 & 0 & 8 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kurangi baris ke-2 dengan baris ke-5 dan bagikan baris ke-5 dengan 8

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kalikan baris ke-5 dengan (-5)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & -5 & -3 & | & 0 & 0 & 0 & 1 & -3 & 0 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & -5 & -15 & | & 0 & 0 & 0 & 0 & 0 & -5 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kurangi baris ke-3 dengan baris ke-5 dan membagikan baris-5 dengan (-5)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kalikan baris ke-5 dengan 2

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 2 & 1 & | & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 2 & 6 & | & 0 & 0 & 0 & 0 & 0 & 2 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kurangi baris ke-4 dengan baris ke-5 dan membagikan baris ke-5 dengan 2

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kalikan baris ke-5 dengan 30

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 30 & 90 & | & 0 & 0 & 0 & 0 & 0 & 30 \\
0 & 0 & 0 & 0 & 30 & 19 & | & 1 & -2 & 5 & -8 & 19 & 0 \
\end{bmatrix}
$$

Kurangi baris ke-6 dengan baris ke-5 dan membagikan baris ke-5 dengan 30

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & -71 & | & 1 & -2 & 5 & -8 & 19 & -30 \
\end{bmatrix}
$$

Membagi baris ke-6 dengan -71

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 1 & | & -1/71 & 2/71 & -5/71 & 8/71 & -19/71 & 30/71\
\end{bmatrix}
$$

Kalikan baris ke-6 dengan 45

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 45 & | & 0 & 1 & -3 & 5 & -12 & 19 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 45 & | & -45/71 & 90/71 & -225/71 & 360/71 & -855/71 & 1350/71\
\end{bmatrix}
$$

Kurangi baris ke-1 dengan baris ke-6 dan membagi baris ke-6 dengan 45

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 1 & | & -1/71 & 2/71 & -5/71 & 8/71 & -19/71 & 30/71\
\end{bmatrix}
$$

Kalikan baris ke-6 dengan (-19)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & -19 & | & 0 & 0 & 1 & -2 & 5 & -8 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & -19 & | & 19/71 & -38/71 & 95/71 & -152/71 & 361/71 & -570/71\
\end{bmatrix}
$$

Kurangi baris ke-2 dengan baris ke-6 dan membagi baris ke-6 dengan (-19)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & 0 & | & -19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 1 & | & -1/71 & 2/71 & -5/71 & 8/71 & -19/71 & 30/71\
\end{bmatrix}
$$

Kalikan baris ke-6 dengan 12

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & 0 & | & -19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
0 & 0 & 1 & 0 & 0 & 12 & | & 0 & 0 & 0 & 1 & -3 & 5 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 12 & | & -12/71 & 24/71 & -60/71 & 96/71 & -228/71 & 360/71\
\end{bmatrix}
$$

Kurangi baris ke-3 dengan baris ke-6 dan membagikan baris ke-6 dengan 12

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & 0 & | & -19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
0 & 0 & 1 & 0 & 0 & 0 & | & 12/71 & -24/71 & 60/71 & -25/71 & 15/71 & -5/71 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 1 & | & -1/71 & 2/71 & -5/71 & 8/71 & -19/71 & 30/71\
\end{bmatrix}
$$

Kalikan baris ke-6 dengan -5

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & 0 & | & -19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
0 & 0 & 1 & 0 & 0 & 0 & | & 12/71 & -24/71 & 60/71 & -25/71 & 15/71 & -5/71 \\
0 & 0 & 0 & 1 & 0 & -5 & | & 0 & 0 & 0 & 0 & 1 & -2 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & -5 & | & 5/71 & -10/71 & 25/71 & -40/71 & 95/71 &-150/71\
\end{bmatrix}
$$

Kurangi baris ke-4 dengan baris ke-6 dan membagi baris ke-6 dengan (-5)

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & 0 & | & -19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
0 & 0 & 1 & 0 & 0 & 0 & | & 12/71 & -24/71 & 60/71 & -25/71 & 15/71 & -5/71 \\
0 & 0 & 0 & 1 & 0 & 0 & | & -5/71 & 10/71 & -25/71 & 40/71 & -24/71 & 8/71 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 1 & | & -1/71 & 2/71 & -5/71 & 8/71 & -19/71 & 30/71\
\end{bmatrix}
$$

Kalikan baris ke-6 dengan 3

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & 0 & | & -19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
0 & 0 & 1 & 0 & 0 & 0 & | & 12/71 & -24/71 & 60/71 & -25/71 & 15/71 & -5/71 \\
0 & 0 & 0 & 1 & 0 & 0 & | & -5/71 & 10/71 & -25/71 & 40/71 & -24/71 & 8/71 \\
0 & 0 & 0 & 0 & 1 & 3 & | & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 3 & | & -3/71 & 6/71 & -15/71 & 24/71 & -57/71 & 90/71\
\end{bmatrix}
$$

Kurangi baris ke-5 dengan baris ke-6 dan membagi baris ke-6 dengan 3

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & 45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
0 & 1 & 0 & 0 & 0 & 0 & | & -19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
0 & 0 & 1 & 0 & 0 & 0 & | & 12/71 & -24/71 & 60/71 & -25/71 & 15/71 & -5/71 \\
0 & 0 & 0 & 1 & 0 & 0 & | & -5/71 & 10/71 & -25/71 & 40/71 & -24/71 & 8/71 \\
0 & 0 & 0 & 0 & 1 & 0 & | & 3/71 & -6/71 & 15/71 & -24/71 & 57/71 & -19/71 \\
0 & 0 & 0 & 0 & 0 & 1 & | & -1/71 & 2/71 & -5/71 & 8/71 & -19/71 & 30/71\
\end{bmatrix}
$$

Sehingga invers matriks yang dihasilkan yaitu

$$
\begin{bmatrix}
45/71 & -19/71 & 12/71 & -5/71 & 3/71 & -1/71 \\
-19/71 & 38/71 & -24/71 & 10/71 & -6/71 & 2/71 \\
12/71 & -24/71 & 60/71 & -25/71 & 15/71 & -5/71 \\
-5/71 & 10/71 & -25/71 & 40/71 & -24/71 & 8/71 \\
3/71 & -6/71 & 15/71 & -24/71 & 57/71 & -19/71 \\
-1/71 & 2/71 & -5/71 & 8/71 & -19/71 & 30/71\
\end{bmatrix}
$$



#### Menentukan matriks invers dengan ordo 6x6 mengguanakan code program

In [6]:
import numpy as np
import sys

# Koefisien matriks 6x6 (ganti dengan koefisien matriks yang sesuai)
a = np.array([[2,1,0,0,0,0], [1,3,1,0,0,0], [0,1,2,1,0,0], [0,0,1,3,1,0], [0,0,0,1,2,1], [0,0,0,0,1,3]])

# Augmentasi dengan matriks identitas 6x6
n = a.shape[0]
identity_matrix = np.identity(n)
augmented_matrix = np.hstack((a, identity_matrix))

# Terapkan Eliminasi Gauss-Jordan
for i in range(n):
    if augmented_matrix[i][i] == 0.0:
        sys.exit('Pembagian dengan nol terdeteksi!')
    for j in range(n):
        if i != j:
            ratio = augmented_matrix[j][i] / augmented_matrix[i][i]
            for k in range(2 * n):
                augmented_matrix[j][k] = augmented_matrix[j][k] - ratio * augmented_matrix[i][k]

# Operasi baris untuk membuat elemen diagonal utama menjadi 1
for i in range(n):
    divisor = augmented_matrix[i][i]
    for j in range(2 * n):
        augmented_matrix[i][j] = augmented_matrix[i][j] / divisor

# Matriks invers
inverse_matrix = augmented_matrix[:, n:]

# Tampilkan matriks invers
print('\nMATRIKS INVERS ADALAH:')
for i in range(n):
    for j in range(n):
        print(inverse_matrix[i][j], end='\t')
    print()


MATRIKS INVERS ADALAH:
0.6338028169014084	-0.2676056338028169	0.16901408450704225	-0.07042253521126761	0.04225352112676056	-0.014084507042253521	
-0.26760563380281693	0.5352112676056339	-0.3380281690140845	0.1408450704225352	-0.08450704225352113	0.02816901408450704	
0.16901408450704222	-0.33802816901408445	0.8450704225352113	-0.352112676056338	0.2112676056338028	-0.07042253521126761	
-0.07042253521126761	0.14084507042253522	-0.352112676056338	0.5633802816901409	-0.3380281690140845	0.11267605633802816	
0.042253521126760556	-0.08450704225352111	0.21126760563380279	-0.33802816901408445	0.8028169014084507	-0.2676056338028169	
-0.014084507042253521	0.028169014084507043	-0.0704225352112676	0.11267605633802817	-0.2676056338028169	0.4225352112676056	


#### Menentukan matriks invers dengan menerapkan RowScale, RowAdd, dan RowSwap

In [7]:
# Import library numpy and memasukkan persamaan dalam bentuk matrix
import numpy as np
A = np.array([[2,1,0,0,0,0], [1,3,1,0,0,0], [0,1,2,1,0,0], [0,0,1,3,1,0], [0,0,0,1,2,1], [0,0,0,0,1,3]])
print(f"Matrix A  = \n{A}")
print("\n")

b = np.array ([1, -2, -1, -1, -1, 2])
print(f"Matrix b =\n{b}")
print("\n")

print("Kita gabungkan setiap kolom Matrix b ke baris Matrix A")
A = np.array([[2,1,0,0,0,0,1], [1,3,1,0,0,0,-2], [0,1,2,1,0,0,-1], [0,0,1,3,1,0,-1], [0,0,0,1,2,1,-1], [0,0,0,0,1,3,2]])
print(f"Matrix A  = \n{A}")
print("\n")

print("Kita juga definisikan Matrix Identitasnya")
B  = np.array([[1,0,0,0,0,0],[0,1,0,0,0,0],[0,0,1,0,0,0],[0,0,0,1,0,0],[0,0,0,0,1,0],[0,0,0,0,0,1]])
print(f"Matrix I = \n{B}")

Matrix A  = 
[[2 1 0 0 0 0]
 [1 3 1 0 0 0]
 [0 1 2 1 0 0]
 [0 0 1 3 1 0]
 [0 0 0 1 2 1]
 [0 0 0 0 1 3]]


Matrix b =
[ 1 -2 -1 -1 -1  2]


Kita gabungkan setiap kolom Matrix b ke baris Matrix A
Matrix A  = 
[[ 2  1  0  0  0  0  1]
 [ 1  3  1  0  0  0 -2]
 [ 0  1  2  1  0  0 -1]
 [ 0  0  1  3  1  0 -1]
 [ 0  0  0  1  2  1 -1]
 [ 0  0  0  0  1  3  2]]


Kita juga definisikan Matrix Identitasnya
Matrix I = 
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [8]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped. (menukarkan persamaan)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A (jumlah baris A)
    n = A.shape[1]  # n is number of columns in A (jumlah kolom A)

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale. (mengalikan entry baris A dengan skala)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modified.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale. (menambahkan nilai baris k dikalikan dengan skala)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [9]:
print("Tukar baris 1 dengan baris 0")
A1 = RowSwap(A,0,1)
print(A1,"\n")
B1 = RowSwap(B,0,1)
print(B1,"\n")

print("R2 = 2R2")
A2 = RowScale (A1,0,2)
print(A2.round(),"\n")
B2 = RowScale (B1,0,2)
print(B2.round(),"\n")

print("R3 = baris ke-2 - baris ke-1")
A3 = A2.copy()
A3 = RowScale (A3, 0, -1)
A3 = RowAdd (A3,0, 1, 1)
print(A3,"\n")
B3 = B2.copy()
B3 = RowScale (B3, 0, -1)
B3 = RowAdd (B3,0, 1, 1)
print(B3,"\n")

print("R4 = (1/-2)R4")
A4 = RowScale (A3,0,1/-2)
print(A4.round(),"\n")
B4 = RowScale (B3,0, 1/-2)
print(B4.round(),"\n")

print("Tukar baris 2 dengan baris 3")
A5 = RowSwap(A4,1,2)
print(A5,"\n")
B5 = RowSwap(B4,1,2)
print(B5,"\n")

print("R6 = 3R6")
A6 = RowScale (A5,1,3)
print(A6.round(),"\n")
B6 = RowScale (B5,1,3)
print(B6.round(),"\n")

print("R7 = baris ke-1 - baris ke-2")
A7 = A6.copy()
A7 = RowScale (A7, 1, -1)
A7 = RowAdd (A7,1, 0, 1)
print(A7,"\n")
B7 = B6.copy()
B7 = RowScale (B7, 1, -1)
B7 = RowAdd (B7,1, 0, 1)
print(B7,"\n")

print("R8 = (1/-3)R8")
A8 = RowScale (A7,1,1/-3)
print(A8.round(),"\n")
B8 = RowScale (B7,1, 1/-3)
print(B8.round(),"\n")

print("R9 = (-5)R9")
A9 = RowScale (A8,1,-5)
print(A9.round(),"\n")
B9 = RowScale (B8,1, -5)
print(B9.round(),"\n")

print("R10 = baris ke-3 - baris ke-2")
A10 = A9.copy()
A10 = RowScale (A10, 1, -1)
A10 = RowAdd (A10,1, 2, 1)
print(A10,"\n")
B10 = B9.copy()
B10 = RowScale (B10, 1, -1)
B10 = RowAdd (B10,1, 2, 1)
print(B10,"\n")

print("R11 = (1/5)R10")
A11 = RowScale (A10,1,1/5)
print(A11.round(),"\n")
B11 = RowScale (B10,1, 1/5)
print(B11.round(),"\n")

print("Tukar baris 4 dengan baris 3")
A12 = RowSwap(A11,3,2)
print(A12,"\n")
B12 = RowSwap(B11,3,2)
print(B12,"\n")

print("R13 = (-5)R13")
A13 = RowScale (A12,2,-5)
print(A13.round(),"\n")
B13 = RowScale (B12,2, -5)
print(B13.round(),"\n")

print("R14 = baris ke-1 - baris ke-3")
A14 = A13.copy()
A14 = RowScale (A14, 2, -1)
A14 = RowAdd (A14,2, 0, 1)
print(A14,"\n")
B14 = B13.copy()
B14 = RowScale (B14, 2, -1)
B14 = RowAdd (B14,2, 0, 1)
print(B14,"\n")

print("R15 = (1/5)R15")
A15 = RowScale (A14,2,1/5)
print(A15.round(),"\n")
B15 = RowScale (B14,2, 1/5)
print(B15.round(),"\n")

print("R16 = (2)R16")
A16 = RowScale (A15,2,2)
print(A16.round(),"\n")
B16 = RowScale (B15,2, 2)
print(B16.round(),"\n")

print("R14 = baris ke-2 - baris ke-3")
A17 = A16.copy()
A17 = RowScale (A17, 2, -1)
A17 = RowAdd (A17,2, 1, 1)
print(A17,"\n")
B17 = B16.copy()
B17 = RowScale (B17, 2, -1)
B17 = RowAdd (B17,2, 1, 1)
print(B17,"\n")

print("R18 = (1/-2)R18")
A18 = RowScale (A17,2,-1/2)
print(A18.round(),"\n")
B18 = RowScale (B17,2, -1/2)
print(B18.round(),"\n")

Tukar baris 1 dengan baris 0
[[ 1.  3.  1.  0.  0.  0. -2.]
 [ 2.  1.  0.  0.  0.  0.  1.]
 [ 0.  1.  2.  1.  0.  0. -1.]
 [ 0.  0.  1.  3.  1.  0. -1.]
 [ 0.  0.  0.  1.  2.  1. -1.]
 [ 0.  0.  0.  0.  1.  3.  2.]] 

[[0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]] 

R2 = 2R2
[[ 2.  6.  2.  0.  0.  0. -4.]
 [ 2.  1.  0.  0.  0.  0.  1.]
 [ 0.  1.  2.  1.  0.  0. -1.]
 [ 0.  0.  1.  3.  1.  0. -1.]
 [ 0.  0.  0.  1.  2.  1. -1.]
 [ 0.  0.  0.  0.  1.  3.  2.]] 

[[0. 2. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]] 

R3 = baris ke-2 - baris ke-1
[[-2. -6. -2. -0. -0. -0.  4.]
 [ 0. -5. -2.  0.  0.  0.  5.]
 [ 0.  1.  2.  1.  0.  0. -1.]
 [ 0.  0.  1.  3.  1.  0. -1.]
 [ 0.  0.  0.  1.  2.  1. -1.]
 [ 0.  0.  0.  0.  1.  3.  2.]] 

[[-0. -2. -0. -0. -0. -0.]
 [ 1. -2.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]


In [10]:
print("R19 = (8)R19")
A19 = RowScale (A18,2,8)
print(A19.round(),"\n")
B19 = RowScale (B18,2, 8)
print(B19.round(),"\n")

print("R20 = baris ke-4 - baris ke-3")
A20 = A19.copy()
A20 = RowScale (A20, 2, -1)
A20 = RowAdd (A20,2, 3, 1)
print(A20,"\n")
B20 = B19.copy()
B20 = RowScale (B20, 2, -1)
B20 = RowAdd (B20,2, 3, 1)
print(B10,"\n")

print("R21 = (1/-8)R21")
A21 = RowScale (A20,2,1/-8)
print(A21.round(),"\n")
B21 = RowScale (B20,2, 1/-8)
print(B21.round(),"\n")

print("Tukar baris 5 dengan baris 4")
A22 = RowSwap(A21,4,3)
print(A22,"\n")
B22 = RowSwap(B21,4, 3)
print(B22,"\n")

print("R23 = (12)R23")
A23 = RowScale (A22,3,12)
print(A23.round(),"\n")
B23 = RowScale (B22,3, 12)
print(B23.round(),"\n")

print("R24 = baris ke-1 - baris ke-4")
A24 = A23.copy()
A24 = RowScale (A24, 3, -1)
A24 = RowAdd (A24,3, 0, 1)
print(A24,"\n")
B24 = B23.copy()
B24 = RowScale (B24, 3, -1)
B24 = RowAdd (B24,3, 0, 1)
print(B24,"\n")

print("R25 = (1/-12)R25")
A25 = RowScale (A24,3,-1/12)
print(A25.round(),"\n")
B25 = RowScale (B24,3, -1/12)
print(B25.round(),"\n")

print("R26 = (-5)R26")
A26 = RowScale (A25,3,-5)
print(A26.round(),"\n")
B26 = RowScale (B25,3, -5)
print(B26.round(),"\n")

print("R27 = baris ke-2 - baris ke-4")
A27 = A26.copy()
A27 = RowScale (A27, 3, -1)
A27 = RowAdd (A27,3, 1, 1)
print(A27,"\n")
B27 = B26.copy()
B27 = RowScale (B27, 3, -1)
B27 = RowAdd (B27,3, 1, 1)
print(B27,"\n")

print("R28 = (1/5)R28")
A28 = RowScale (A27,3,1/5)
print(A28.round(),"\n")
B28 = RowScale (B27,3, 1/5)
print(B28.round(),"\n")

print("R29 = (3)R29")
A29 = RowScale (A28,3,3)
print(A29.round(),"\n")
B29 = RowScale (B28,3, 3)
print(B29.round(),"\n")

print("R30 = baris ke-3 - baris ke-4")
A30 = A29.copy()
A30 = RowScale (A30, 3, -1)
A30 = RowAdd (A30,3, 2, 1)
print(A30,"\n")
B30 = B29.copy()
B30 = RowScale (B30, 3, -1)
B30 = RowAdd (B30,3, 2, 1)
print(B30,"\n")

print("R31 = (-1/3)R31")
A31 = RowScale (A30,3,-1/3)
print(A31.round(),"\n")
B31 = RowScale (B30,3, -1/3)
print(B31.round(),"\n")

print("R32 = (-19)R32")
A32 = RowScale (A31,3,-19)
print(A32.round(),"\n")
B32 = RowScale (B31,3, -19)
print(B32.round(),"\n")

print("R33 = baris ke-5 - baris ke-4")
A33 = A32.copy()
A33 = RowScale (A33, 3, -1)
A33 = RowAdd (A33,3, 4, 1)
print(A33,"\n")
B33 = B32.copy()
B33 = RowScale (B33, 3, -1)
B33 = RowAdd (B33,3, 4, 1)
print(B33,"\n")

print("R34 = (1/-19)R34")
A34 = RowScale (A33,3,1/19)
print(A34.round(),"\n")
B34 = RowScale (B33,3, 1/19)
print(B34.round(),"\n")

print("Tukar baris 6 dengan baris 5")
A35 = RowSwap(A34,4,5)
print(A35,"\n")
B35 = RowSwap(B34,4, 5)
print(B35,"\n")

print("R36 = (-19)R36")
A36 = RowScale (A35,4,-19)
print(A36.round(),"\n")
B36 = RowScale (B35,4, -19)
print(B36.round(),"\n")

print("R37 = baris ke-1 - baris ke-5")
A37 = A36.copy()
A37 = RowScale (A37, 4, -1)
A37 = RowAdd (A37,4, 0, 1)
print(A37,"\n")
B37 = B36.copy()
B37 = RowScale (B37, 4, -1)
B37 = RowAdd (B37,4, 0, 1)
print(B37,"\n")

print("R38 = (1/-19)R38")
A38 = RowScale (A37,4,1/19)
print(A38.round(),"\n")
B38 = RowScale (B37,4, 1/19)
print(B38.round(),"\n")

print("R39 = (8)R39")
A39 = RowScale (A38,4,8)
print(A39.round(),"\n")
B39 = RowScale (B38,4, 8)
print(B39.round(),"\n")

print("R40 = baris ke-2 - baris ke-5")
A40 = A39.copy()
A40 = RowScale (A40, 4, -1)
A40 = RowAdd (A40,4, 1, 1)
print(A40,"\n")
B40 = B39.copy()
B40 = RowScale (B40, 4, -1)
B40 = RowAdd (B40,4, 1, 1)
print(B40,"\n")

print("R41 = (-1/8)R40")
A41 = RowScale (A40,4,-1/8)
print(A41.round(),"\n")
B41 = RowScale (B40,4, -1/8)
print(B41.round(),"\n")

print("R42 = (-5)R42")
A42 = RowScale (A41,4,-5)
print(A42.round(),"\n")
B42 = RowScale (B41,4, -5)
print(B42.round(),"\n")

print("R43 = baris ke-3 - baris ke-5")
A43 = A42.copy()
A43 = RowScale (A43, 4, -1)
A43 = RowAdd (A43,4, 2, 1)
print(A43,"\n")
B43 = B42.copy()
B43 = RowScale (B43, 4, -1)
B43 = RowAdd (B43,4, 2, 1)
print(B43,"\n")

print("R44 = (1/5)R44")
A44 = RowScale (A43,4,1/5)
print(A44.round(),"\n")
B44 = RowScale (B43,4, 1/5)
print(B44.round(),"\n")

R19 = (8)R19
[[ 1.  0.  0. 12.  5.  0. -4.]
 [ 0.  1.  0. -5. -2.  0.  1.]
 [ 0.  0.  8. 24.  8.  0. -8.]
 [ 0.  0.  8.  5.  0.  0.  0.]
 [ 0.  0.  0.  1.  2.  1. -1.]
 [ 0.  0.  0.  0.  1.  3.  2.]] 

[[ 0.  1. -3.  5.  0.  0.]
 [ 0.  0.  1. -2.  0.  0.]
 [ 0.  0.  0.  8.  0.  0.]
 [ 1. -2.  5.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]] 

R20 = baris ke-4 - baris ke-3
[[  1.   0.   0.  12.   5.   0.  -4.]
 [  0.   1.   0.  -5.  -2.   0.   1.]
 [ -0.  -0.  -8. -24.  -8.  -0.   8.]
 [  0.   0.   0. -19.  -8.   0.   8.]
 [  0.   0.   0.   1.   2.   1.  -1.]
 [  0.   0.   0.   0.   1.   3.   2.]] 

[[ 0.  1. -3.  0.  0.  0.]
 [ 0.  0.  5.  0.  0.  0.]
 [ 1. -2.  5.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]] 

R21 = (1/-8)R21
[[  1.   0.   0.  12.   5.   0.  -4.]
 [  0.   1.   0.  -5.  -2.   0.   1.]
 [  0.   0.   1.   3.   1.   0.  -1.]
 [  0.   0.   0. -19.  -8.   0.   8.]
 [  0.   0.   0.   1.   2.   1.  -1.]
 

In [12]:
print("R45 = (2)R45")
A45 = RowScale (A44,4,2)
print(A45.round(),"\n")
B45 = RowScale (B44,4, 2)
print(B45.round(),"\n")

print("R46 = baris ke-4 - baris ke-5")
A46 = A45.copy()
A46 = RowScale (A46, 4, -1)
A46 = RowAdd (A46,4, 3, 1)
print(A46,"\n")
B46 = B45.copy()
B46 = RowScale (B46, 4, -1)
B46 = RowAdd (B46,4, 3, 1)
print(B46,"\n")

print("R47 = (-1/2)R47")
A47 = RowScale (A46,4,-1/2)
print(A47.round(),"\n")
B47 = RowScale (B46,4, -1/2)
print(B47.round(),"\n")

print("R48 = (30)R48")
A48 = RowScale (A47,4,30)
print(A48.round(),"\n")
B48 = RowScale (B47,4, 30)
print(B48.round(),"\n")

print("R49 = baris ke-6 - baris ke-5")
A49 = A48.copy()
A49 = RowScale (A49, 4, -1)
A49 = RowAdd (A49,4, 5, 1)
print(A49,"\n")
B49 = B48.copy()
B49 = RowScale (B49, 4, -1)
B49 = RowAdd (B49,4, 5, 1)
print(B49,"\n")

print("R50 = (-1/30)R50")
A50 = RowScale (A49,4,-1/30)
print(A50.round(),"\n")
B50 = RowScale (B49,4, -1/30)
print(B50.round(),"\n")

print("R51 = (-1/71)R51")
A51 = RowScale (A50,5,-1/71)
print(A51,"\n")
B51 = RowScale (B50,5, -1/71)
print(B51,"\n")

print("R52 = (45)R52")
A52 = RowScale (A51,5,45)
print(A52,"\n")
B52 = RowScale (B51,5, 45)
print(B52,"\n")

print("R53 = baris ke-1 - baris ke-6")
A53 = A52.copy()
A53 = RowScale (A53, 5, -1)
A53 = RowAdd (A53,5, 0, 1)
print(A53,"\n")
B53 = B52.copy()
B53 = RowScale (B53, 5, -1)
B53 = RowAdd (B53,5, 0, 1)
print(B53,"\n")

print("R54 = (1/-45)R54")
A54 = RowScale (A53,5,-1/45)
print(A54,"\n")
B54 = RowScale (B53,5, -1/45)
print(B54,"\n")

print("R55 = (-19)R55")
A55 = RowScale (A54,5,-19)
print(A55,"\n")
B55 = RowScale (B54,5,-19)
print(B55,"\n")

print("R56 = baris ke-2 - baris ke-6")
A56 = A55.copy()
A56 = RowScale (A56, 5, -1)
A56 = RowAdd (A56,5, 1, 1)
print(A56,"\n")
B56 = B55.copy()
B56 = RowScale (B56, 5, -1)
B56 = RowAdd (B56,5, 1, 1)
print(B56,"\n")

print("R57 = (1/19)R57")
A57 = RowScale (A56,5,1/19)
print(A57,"\n")
B57 = RowScale (B56,5,1/19)
print(B57,"\n")

print("R58 = (12)R58")
A58 = RowScale (A57,5,12)
print(A58,"\n")
B58 = RowScale (B57,5,12)
print(B58,"\n")

print("R59 = baris ke-3 - baris ke-6")
A59 = A58.copy()
A59 = RowScale (A59, 5, -1)
A59 = RowAdd (A59,5, 2, 1)
print(A59,"\n")
B59 = B58.copy()
B59 = RowScale (B59, 5, -1)
B59 = RowAdd (B59,5, 2, 1)
print(B59,"\n")

print("R60 = (1/-12)R60")
A60 = RowScale (A59,5,-1/12)
print(A60,"\n")
B60 = RowScale (B59,5,-1/12)
print(B60,"\n")

print("R61 = (-5)R61")
A61 = RowScale (A60,5,-5)
print(A61,"\n")
B61 = RowScale (B60,5,-5)
print(B61,"\n")


print("R62 = baris ke-4 - baris ke-6")
A62 = A61.copy()
A62 = RowScale (A62, 5, -1)
A62 = RowAdd (A62,5, 3, 1)
print(A62,"\n")
B62 = B61.copy()
B62 = RowScale (B62, 5, -1)
B62 = RowAdd (B62,5, 3, 1)
print(B62,"\n")

print("R63 = (15)R63")
A63 = RowScale (A62,5,1/5)
print(A63,"\n")
B63 = RowScale (B62,5,1/5)
print(B63,"\n")

print("R64 = (3)R64")
A64 = RowScale (A63,5,3)
print(A64,"\n")
B64 = RowScale (B63,5,3)
print(B64,"\n")

print("R65 = baris ke-5 - baris ke-6")
A65 = A64.copy()
A65 = RowScale (A65, 5, -1)
A65 = RowAdd (A65,5, 4, 1)
print(A65,"\n")
B65 = B64.copy()
B65 = RowScale (B65, 5, -1)
B65 = RowAdd (B65,5, 4, 1)
print(B65,"\n")

print("R66 = (1/-3)R66")
A66 = RowScale (A65,5,-1/3)
print(A66,"\n")
B66 = RowScale (B65,5,-1/3)
print(B66,"\n")

print("Sehingga matriks invers yang dihasilkan yaitu :")
print(B66,"\n")

print ("sehingga nilai variabel yang didapat yaitu :")
print (" x = 1")
print (" y = -1")
print (" z = 0")
print (" w = 0")
print (" u = -1")
print (" v = 1")

print ("Pembuktian :")
print ("2x+y+0z+0w+0u+0v=1 = 2(1) + (-1) + 0(0) + 0(0) + 0(-1) + 0(1) = 1 ")
print ("x+3y+z+0w+0u+0v=−2 = (1) + 3(-1) + 0 + 0 (0) + 0(-1) + 0(1) = -2")
print ("0x+y+2z+w+0u+0v=−1 = 0(1) + (-1) + 2(0) + 0 + 0(-1) + 0(1) = -1")
print ("0x+0y+z+3w+u+0v=−1 = 0(1) + 0(-1) + 0 + 3(0) + (-1) + 0(1) = -1")
print ("0x+0y+0z+w+2u+v=−1 = 0(1) + 0(-1) + 0(0) + 0 + 2(-1) + 1 = -1")
print ("0x+0y+0z+0w+u+3v=2 = 0(1) + 0(-1) + 0(0) + 0(0) + -1 + 3(1) = 2 ")

R45 = (2)R45
[[  1.   0.   0.   0.   0.  45.  46.]
 [  0.   1.   0.   0.   0. -19. -20.]
 [  0.   0.   1.   0.   0.  12.  12.]
 [  0.   0.   0.   1.   2.   1.  -1.]
 [  0.   0.   0.   0.   2.   6.   4.]
 [  0.   0.   0.   0.  30.  19. -11.]] 

[[  0.   1.  -3.   5. -12.  19.]
 [  0.   0.   1.  -2.   5.  -8.]
 [  0.   0.   0.   1.  -3.   5.]
 [  0.   0.   0.   0.   1.   0.]
 [  0.   0.   0.   0.   0.   2.]
 [  1.  -2.   5.  -8.  19.   0.]] 

R46 = baris ke-4 - baris ke-5
[[  1.   0.   0.   0.   0.  45.  46.]
 [  0.   1.   0.   0.   0. -19. -20.]
 [  0.   0.   1.   0.   0.  12.  12.]
 [  0.   0.   0.   1.   0.  -5.  -5.]
 [ -0.  -0.  -0.  -0.  -2.  -6.  -4.]
 [  0.   0.   0.   0.  30.  19. -11.]] 

[[  0.   1.  -3.   5. -12.  19.]
 [  0.   0.   1.  -2.   5.  -8.]
 [  0.   0.   0.   1.  -3.   5.]
 [  0.   0.   0.   0.   1.  -2.]
 [ -0.  -0.  -0.  -0.  -0.  -2.]
 [  1.  -2.   5.  -8.  19.   0.]] 

R47 = (-1/2)R47
[[  1.   0.   0.   0.   0.  45.  46.]
 [  0.   1.   0.   0.   0. -19. -20.]
 

#### Membuktikan bahwa "Jika matriks A dikalikan dengan invers matriks A akan menghasilkan matriks identitas"

In [ ]:
import numpy as np

# Matriks koefisien persamaan
Invers_Matriks_A = np.array([[45/71, -19/71, 12/71, -5/71, 3/71, -1/71],
              [-19/71, 38/71, -24/71, 10/71, -6/71, 2/71],
              [12/71, -24/71, 60/71, -25/71, 15/71, -5/71],
              [-5/71, 10/71, -25/71, 40/71, -24/71, 8/71],
              [3/71, -6/71, 15/71, -24/71, 57/71, -19/71],
              [-1/71, 2/71, -5/71, 8/71, -19/71, 30/71]])

# Matriks hasil persamaan
Matriks_A = np.array([[2,1,0,0,0,0], [1,3,1,0,0,0], [0,1,2,1,0,0], [0,0,1,3,1,0], [0,0,0,1,2,1], [0,0,0,0,1,3]])

# Mengalikan matriks A dengan matriks invers matriks A
result = np.dot(Invers_Matriks_A, Matriks_A)

# Memperoleh hasil yang dibulatkan
Hasil = np.round(result)
Hasil[Hasil < 0] = 0
Hasil[Hasil != 1] = 0

# Menampilkan hasil
print("Hasil:")
print(Hasil)
print ('Terbukti bahwa matriks A dikalikan dengan invers matriks A akan menghasilkan matriks identitas')

Hasil:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Terbukti bahwa matriks A dikalikan dengan invers matriks A akan menghasilkan matriks identitas
