
# ALJABAR MATRIKS

Matriks adalah sekumpulan bilangan yang disusun berdasarkan baris dan kolom, serta ditempatkan di dalam tanda kurung. Bilangan-bilangan yang membentuk suatu matriks disebut sebagai elemen-elemen matriks. Matriks digunakan untuk menyederhanakan penyampaian data, sehingga mudah untuk diolah



## Operasi matrik (penjumlahan, perkalian, pengurangan, transpose)



### Penjumlahan Matrik
Syarat Penjumlahan Matriks:

*   Dua matriks dapat dijumlahkan jika jumlah baris dan kolomnya sama
*   Matriks hasil penjumlahan juga akan memiliki ordo yang sama.

In [ ]:
import numpy as np
import sympy as sy

A=np.array([[2, -3, 4], [1, 0, -7]])
B=np.array([[6, 2, -4], [3, 5, 2]])
print ('matriks A=\n', A)
print ('matriks B=\n', B)

matriks A=
 [[ 2 -3  4]
 [ 1  0 -7]]
matriks B=
 [[ 6  2 -4]
 [ 3  5  2]]


In [ ]:
import numpy as np
import sympy as sy

Hasil_Penjumlahan=np.array([[2+6, -3+2, 4+(-4)], [1+3, 0+5, -7+2]])
print ('A + B =\n', Hasil_Penjumlahan )

A - B =
 [[ 8 -1  0]
 [ 4  5 -5]]


Pada contoh tersebut terdapat matriks A dan B.

Dimisalkan matriks A (ordo 2 x 3):

A = 2

B = -3

C = 4

D = 1

E = 0

F = -7

Sedangkan untuk matriks B (ordo 2 x 3) yaitu :

G = 6

H = 2

I = -4

J = 3

K = 5

L = 2

Sehingga untuk menjumlahkan kedua matriks tersebut dapat dilakukan dengan cara sebagai berikut :


A + B =

|       | kolom 1 | kolom 2 | kolom 3 |
|-------|---------|--------|-------|
| Baris 1 |  A + G |  B + H | C + I  |
| Baris 2 |  D + J  |  E + K  | F + L |



A + B =

|       | kolom 1 | kolom 2 | kolom 3 |
|-------|---------|--------|-------|
| Baris 1 |  2 + 6 |  -3 + 2 | 4 + (-4)  |
| Baris 2 |  1 + 3  |  0 + 5 | -7 + 2 |

A + B =

|       | kolom 1 | kolom 2 | kolom 3 |
|-------|---------|--------|-------|
| Baris 1 |  8 |  -1 | 0  |
| Baris 2 |  4 |  5 | -5 |

Berikut program yang digunakan untuk menjumlahkan matrik

In [ ]:
import numpy as np
import sympy as sy

A=np.array([[1, -4, 3],[6, 9, 2],[6, 3, 1]])
B=np.array([[9,-1,3],[6,4,1],[2,-2,1]])
C=np.array([[8,4],[-3,1],[7,4]])
print('A=\n',A)
print('B=\n',B)
print('C=\n',C)

#Penjumlahan Matrik
print('A+B=\n',A+B)
print('B+A=\n',B+A)
print('Hasil A+B = B+A (KOMUTATIF)')

A=
 [[ 1 -4  3]
 [ 6  9  2]
 [ 6  3  1]]
B=
 [[ 9 -1  3]
 [ 6  4  1]
 [ 2 -2  1]]
C=
 [[ 8  4]
 [-3  1]
 [ 7  4]]
A+B=
 [[10 -5  6]
 [12 13  3]
 [ 8  1  2]]
B+A=
 [[10 -5  6]
 [12 13  3]
 [ 8  1  2]]
Hasil A+B = B+A (KOMUTATIF)


### Pengurangan Matriks
Syarat utama untuk melakukan pengurangan matriks adalah :

*   Dua atau lebih matriks dapat dikurangkan jika memiliki nilai ordo yang sama.
*   Matriks hasil pengurangan juga akan memiliki ordo yang sama.




In [ ]:
import numpy as np
import sympy as sy

A=np.array([[2, -3, 4], [1, 0, -7]])
B=np.array([[6, 2, -4], [3, 5, 2]])
print ('matriks A=\n', A)
print ('matriks B=\n', B)

matriks A=
 [[ 2 -3  4]
 [ 1  0 -7]]
matriks B=
 [[ 6  2 -4]
 [ 3  5  2]]


Pada contoh tersebut terdapat matriks A dan B.

Dimisalkan matriks A (ordo 2 x 3):

A = 2

B = -3

C = 4

D = 1

E = 0

F = -7

Sedangkan untuk matriks B (ordo 2 x 3) yaitu :

G = 6

H = 2

I = -4

J = 3

K = 5

L = 2

Sehingga untuk mengurangi kedua matriks tersebut dapat dilakukan sebagai berikut :



In [ ]:
import numpy as np
import sympy as sy

Hasil_Pengurangan=np.array([[2-6, -3-2, 4-(-4)], [1-3, 0-5, -7-2]])
print ('A - B =\n', Hasil_Pengurangan )

A - B =
 [[-4 -5  8]
 [-2 -5 -9]]


Berdasarkan program diatas dapat disimpulkan bahwa dalam mengurangi sebuah matriks dapat dilakukan sebagai berikut

A - B =

|       | kolom 1 | kolom 2 | kolom 3 |
|-------|---------|--------|-------|
| Baris 1 |  A - G |  B - H | C - I  |
| Baris 2 |  D - J  |  E - K  | F - L |



A - B =

|       | kolom 1 | kolom 2 | kolom 3 |
|-------|---------|--------|-------|
| Baris 1 |  2 - 6 |  -3 - 2 | 4 - (-4)  |
| Baris 2 |  1 - 3  |  0 - 5 | -7 - 2 |

A - B =

|       | kolom 1 | kolom 2 | kolom 3 |
|-------|---------|--------|-------|
| Baris 1 |  -4 |  -5 | 8  |
| Baris 2 |  -2  |  -5 | -9 |

Berikut program yang digunakan untuk mengurangi matrik :

In [ ]:
import numpy as np
import sympy as sy

A=np.array([[1, -4, 3],[6, 9, 2],[6, 3, 1]])
B=np.array([[9,-1,3],[6,4,1],[2,-2,1]])
C=np.array([[8,4],[-3,1],[7,4]])
print('A=\n',A)
print('B=\n',B)
print('C=\n',C)

#Pengurangan Matrik
print('A-B=\n',A-B)
print('B-A=\n',B-A)
print('Hasil A-B = B-A (BUKAN KOMUTATIF)')



A=
 [[ 1 -4  3]
 [ 6  9  2]
 [ 6  3  1]]
B=
 [[ 9 -1  3]
 [ 6  4  1]
 [ 2 -2  1]]
C=
 [[ 8  4]
 [-3  1]
 [ 7  4]]
A-B=
 [[-8 -3  0]
 [ 0  5  1]
 [ 4  5  0]]
B-A=
 [[ 8  3  0]
 [ 0 -5 -1]
 [-4 -5  0]]
Hasil A-B = B-A (BUKAN KOMUTATIF)


### Perkalian Matrik

*  Untuk melakukan perkalian matriks, mengalikan setiap baris dari matriks pertama dengan setiap kolom dari matriks kedua, kemudian menjumlahkan hasilnya.
*   Syarat utama untuk perkalian matriks adalah jumlah kolom matriks pertama harus sama dengan jumlah baris matriks kedua.


In [ ]:
import numpy as np
import sympy as sy

A=np.array([[2, 3], [1, 4]])
B=np.array([[3, 5], [2, 1]])
print ('matriks A=\n', A)
print ('matriks B=\n', B)

matriks A=
 [[2 3]
 [1 4]]
matriks B=
 [[3 5]
 [2 1]]


Pada contoh tersebut terdapat matriks A dan B.

Dimisalkan matriks A (ordo 2 x 2):

A = 2

B = 3

C = 1

D = 4

Sedangkan untuk matriks B (ordo 2 x 2) yaitu :

E = 3

F = 5

G = 2

H = 1

Sehingga untuk mengalikan kedua matriks tersebut dapat dilakukan sebagai berikut :

A X B =

|       | kolom 1 | kolom 2 |
|-------|---------|--------|
| Baris 1 |  (A x E)+(B x G) |  (A x F)+(B x H) |
| Baris 2 |  (C x E)+(D x G)  |  (C x F)+(D x H)  |



A X B =

|       | kolom 1 | kolom 2 |
|-------|---------|--------|
| Baris 1 |  (2 x 3)+(3 x 2) |  (2 x 5)+(3 x 1) |
| Baris 2 |  (1 x 3)+(4 x 2)  |  (1 x 5)+(4 x 1)  |

A X B =

|       | kolom 1 | kolom 2 |
|-------|---------|--------|
| Baris 1 |  6+6 |  10+3 |
| Baris 2 |  3+8  |  5+4  |


A X B =

|       | kolom 1 | kolom 2 |
|-------|---------|--------|
| Baris 1 |  12 |  13 |
| Baris 2 | 11  |  9  |

Berikut program yang digunakan untuk mengalikan matrik :

In [ ]:
#Buat program untuk mengalikan matrik A dan B (menggunakan for)
# Matriks A dan B (contoh)
A = [[3, 9], [1, 3]]
B = [[9, 4,1], [8, 2, 8]]

# Inisialisasi matriks hasil
result = []

# Perkalian matriks menggunakan nested for loop
for i in range(len(A)):
    row = []  # Baris baru pada matriks hasil
    for j in range(len(B[0])):
        product = 0  # Elemen baru pada baris hasil
        for v in range(len(A[i])):
            product += A[i][v] * B[v][j]
        row.append(product)  # Menambahkan hasil perkalian ke baris baru
    result.append(row)  # Menambahkan baris baru ke hasil akhir

# Menampilkan hasil perkalian matriks
for row in result:
    print(row)

[99, 30, 75]
[33, 10, 25]


Membuat program dalam mengalikan matriks juga dapat dilakukan dengan menggunakan numpy

In [ ]:
import numpy as np
import sympy as sy

A=np.array([[1, -4, 3],[6, 9, 2],[6, 3, 1]])
B=np.array([[9,-1,3],[6,4,1],[2,-2,1]])
C=np.array([[8,4],[-3,1],[7,4]])
print('A=\n',A)
print('B=\n',B)
print('C=\n',C)
#Perkalian Matrik
print('AB=\n',A@B)
print('AC=\n',A@C)
print('BC=\n',B@C)


A=
 [[ 1 -4  3]
 [ 6  9  2]
 [ 6  3  1]]
B=
 [[ 9 -1  3]
 [ 6  4  1]
 [ 2 -2  1]]
C=
 [[ 8  4]
 [-3  1]
 [ 7  4]]
AB=
 [[ -9 -23   2]
 [112  26  29]
 [ 74   4  22]]
AC=
 [[41 12]
 [35 41]
 [46 31]]
BC=
 [[96 47]
 [43 32]
 [29 10]]


Perbedaan program yang menggunakan for dan numpy terletak pada cara pembuatan programnya. Pada program yang menggunakan numpy lebih mudah dikarenakan program tersebut akan langsung menjalankan perintah dari user. Sebagai contoh pada perkalian matriks tersebut terdapat tanda (@) disimbolkan sebagai tanda 'perkalian' sehingga ketika program dijalankan akan langsung mengalikan matriks tersebut.

Sedangkan program yang menggunakan for dapat dilihat bahwa dalam membuat programnya lebih rumit dan lebih banyak, dikarenakan program yang dibuat terdapat langkah-langkah yang harus dilakukan satu per satu. Seperti contoh pada program for (perkalian) yang dimana program tersebut harus menambahkan hasil perkalian ke baris baru, menambahkan baris baru ke hasil akhir, yang tentunya juga membutuhkan waktu lama dalam membuat programnya. Sehingga kesimpulannya yaitu dalam penggunaan numpy dalam membuat suatu program lebih efisien dikarenakan pembuatannya yang lebih mudah dan juga memerlukan waktu yang singkat

### Perkalian Skalar Matriks
Perkalian skalar matriks adalah operasi matematika yang melibatkan mengalikan setiap elemen dalam suatu matriks dengan sebuah skalar (konstanta).

*   Jika memiliki matriks A dan sebuah skalar C, maka hasil perkalian skalar matriks A dengan C adalah matriks yang elemen-elemennya diperoleh dengan mengalikan setiap elemen matriks A dengan C.


In [ ]:
import numpy as np
import sympy as sy

A=np.array([[2, 8], [-3, 5], [0, 1]])
print ('matriks A=\n', A)

matriks A=
 [[ 2  8]
 [-3  5]
 [ 0  1]]


Pada contoh tersebut terdapat matriks A dengan ordo (3 x 2)

Dapat dimisalkan bahwa :

A = 2

B = 8

C = -3

D = 5

E = 0

F = 1

Misalkan skalar yang mempunyai nilai 7, sehingga perkalian skalar yang akan dihasilan yaitu:

In [ ]:
import numpy as np
import sympy as sy

A=np.array([[2*7, 8*7], [-3*7, 5*7], [0*7, 1*7]])
print ('matriks A=\n', A)

matriks A=
 [[ 14  56]
 [-21  35]
 [  0   7]]


Berdasarkan program diatas dapat disimpulkan bahwa dalam mengalikan sebuah matriks dengan skalar dapat dilakukan dengan cara sebagai berikut :

C x A = 7 x A

|       | kolom 1 | kolom 2 |
|-------|---------|--------|
| Baris 1 |  A x 7 |  B X 7 |
| Baris 2 |  C x 7  |  D x 7  |
| Baris 3 |  E x 7 |  F x 7  |

C x A = 7 x A

|       | kolom 1 | kolom 2 |
|-------|---------|--------|
| Baris 1 |  2 x 7 |  8 X 7 |
| Baris 2 |  -3 x 7  |  5 x 7  |
| Baris 3 |  0 x 7 |  1 x 7  |

C x A = 7 x A

|       | kolom 1 | kolom 2 |
|-------|---------|--------|
| Baris 1 |  14 |  56 |
| Baris 2 |  -21  |  35  |
| Baris 3 |   0   |  7  |

Berikut program yang digunakan untuk mengalikan suatu matrik dengan skalar:

In [ ]:
import numpy as np
import sympy as sy

A=np.array([[1, -4, 3],[6, 9, 2],[6, 3, 1]])
B=np.array([[9,-1,3],[6,4,1],[2,-2,1]])
C=np.array([[8,4],[-3,1],[7,4]])
print('A=\n',A)
print('B=\n',B)
print('C=\n',C)
#Perkalian Skalar
c = 7
print('c(AB)\n',c*(A@B))
print('(cA)B\n',(c*A)@B)
print('A(cB)\n',A@(c*B))
print('Hasil c(AB) = (cA)B = A(cB)')


A=
 [[ 1 -4  3]
 [ 6  9  2]
 [ 6  3  1]]
B=
 [[ 9 -1  3]
 [ 6  4  1]
 [ 2 -2  1]]
C=
 [[ 8  4]
 [-3  1]
 [ 7  4]]
c(AB)
 [[ -63 -161   14]
 [ 784  182  203]
 [ 518   28  154]]
(cA)B
 [[ -63 -161   14]
 [ 784  182  203]
 [ 518   28  154]]
A(cB)
 [[ -63 -161   14]
 [ 784  182  203]
 [ 518   28  154]]
Hasil c(AB) = (cA)B = A(cB)


### Transpose Matriks
Transpose matriks adalah operasi matematika yang menghasilkan matriks baru dengan menukar elemen-elemen baris menjadi elemen kolom atau sebaliknya



In [4]:
import numpy as np
import sympy as sy

A=np.array([[3, 7, 2, -3],[-1, 4, 2, 8],[0, 3, -2, 5]])
print ('matriks A=\n', A)

matriks A=
 [[ 3  7  2 -3]
 [-1  4  2  8]
 [ 0  3 -2  5]]


Pada contoh tersebut terdapat matriks A dengan ordo (3 x 4)

Dapat dimisalkan bahwa :

A = 3

B = 7

C = 2

D = -3

E = -1

F = 4

G = 2

H = 8

I = 0

J = 3

K = -2

L = 5

Sehingga transpose matriks A yang akan dihasilan yaitu:

In [5]:
import numpy as np
import sympy as sy

A=np.array([[3, -1, 0],[7, 4, 3],[2, 2, -2], [-3, 8, 5]])
print ('Transpose matriks A=\n', A)

Transpose matriks A=
 [[ 3 -1  0]
 [ 7  4  3]
 [ 2  2 -2]
 [-3  8  5]]


Berdasarkan program diatas dapat disimpulkan bahwa dalam mentranspose sebuah matriks dapat dilakukan dengan cara sebagai berikut :

Matriks A =

|       | kolom 1 | kolom 2 | kolom 3 | kolom 4 |
|-------|---------|--------|--------|--------|
| Baris 1 |  A  |  B  |  C  |  D  |
| Baris 2 |  E  |  F  | G  |  H  |
| Baris 3 |   I  |  J  | K  |  L  |

Transpose Matriks A =

|       | kolom 1 | kolom 2 | kolom 3 |
|-------|---------|--------|--------|
| Baris 1 |  A |  E | I  |
| Baris 2 |  B |  F | J  |
| Baris 3 |  C |  G | K  |
| Baris 4 |  D |  H | L  |

Matriks A =

|       | kolom 1 | kolom 2 | kolom 3 | kolom 4 |
|-------|---------|--------|--------|--------|
| Baris 1 |  3  |  7  |  2  |  -3  |
| Baris 2 |  -1  |  4  | 2  |  8  |
| Baris 3 |   0  |  3  | -2  |  5  |

Transpose Matriks A =

|       | kolom 1 | kolom 2 | kolom 3 |
|-------|---------|--------|--------|
| Baris 1 |  3 |  -1 | 0  |
| Baris 2 |  7 |  4 | 3  |
| Baris 3 |  2 |  2 | -2  |
| Baris 4 |  -3 |  8 | 5  |


Berikut program yang digunakan untuk mentranspose suatu matrik:

In [ ]:
import numpy as np
import sympy as sy

A=np.array([[1, -4, 3],[6, 9, 2],[6, 3, 1]])
B=np.array([[9,-1,3],[6,4,1],[2,-2,1]])
C=np.array([[8,4],[-3,1],[7,4]])
print('A=\n',A)
print('B=\n',B)
print('C=\n',C)
#Tranpose Matrik
C_trans = C.transpose()
print('matrik c sebelum di transpose=\n', C)
print('matrik c setelah di transpose=\n',C_trans)
print('ordo C_transpose adalah',C_trans.shape)
z=C_trans@C
print('Z = C_transpose x C =\n',z)
print('ordo z adalah',z.shape)
p=C@C_trans
print('P = C_transpose x C =\n',p)
print('ordo P adalah',p.shape)


A=
 [[ 1 -4  3]
 [ 6  9  2]
 [ 6  3  1]]
B=
 [[ 9 -1  3]
 [ 6  4  1]
 [ 2 -2  1]]
C=
 [[ 8  4]
 [-3  1]
 [ 7  4]]
matrik c sebelum di transpose=
 [[ 8  4]
 [-3  1]
 [ 7  4]]
matrik c setelah di transpose=
 [[ 8 -3  7]
 [ 4  1  4]]
ordo C_transpose adalah (2, 3)
Z = C_transpose x C =
 [[122  57]
 [ 57  33]]
ordo z adalah (2, 2)
P = C_transpose x C =
 [[ 80 -20  72]
 [-20  10 -17]
 [ 72 -17  65]]
ordo P adalah (3, 3)
