##Aljabar Matrik
Tidak mengerjakan tidak boleh masuk

*   Berikan penjelasan tentang apa itu matrik

Matriks adalah sekumpulan bilangan yang disusun berdasarkan baris dan kolom, serta ditempatkan di dalam tanda kurung. Bilangan-bilangan yang membentuk suatu matriks disebut sebagai elemen-elemen matriks. Matriks digunakan untuk menyederhanakan penyampaian data, sehingga mudah untuk diolah

Matrik A dan C = m x n
Matrik B = n x k
*   Operasi matrik (penjumlahan, perkalian, pengurangan, tranpose)

penjumlahan dan pengurangan matriks yaitu : jika terdapat dua matriks, misal matriks A dan B, yang memiliki ordo sama, maka elemen-elemen yang seletak dapat dijumlahkan atau dikurangkan. Jumlah matriks A dan matriks B dapat dinyatakan dengan A+B, sedangkan selisih matriks A dan matriks B dapat dinyatakan dengan A – B. Untuk mencari hasil kali matriks A dengan matriks B ialah dengan mengalikan elemen pada baris-baris matriks A dengan elemen pada kolom-kolom matriks B, kemudian jumlahkan hasil perkalian antara baris dan kolom tersebut. Berbeda dengan perkalian skalar yang hanya mengalikan setiap elemen matriks dengan bilangan skalar, perkalian dua matriks memiliki aturan tersendiri.  Syarat dua buah matriks, misal matriks A dan matriks B, dapat dikalikan adalah jika banyaknya kolom matriks A sama dengan banyaknya baris matriks B. Transpose suatu matriks, misal matriks A, yang dilambangkan dengan At adalah sebuah matriks yang disusun dengan cara menukarkan baris matriks A menjadi kolom matriks At dan kolom matriks A menjadi baris matriks At.

Perkalian matrik A, B, C, dan c skalar adalah sebagai berikut:

*   A(BC)= (AB)C
*   c(AB)= (cA)B=(cB)A
*   A (B+C) = AB+ AC
*   (B+C)A = BA + CA


*   Buat program untuk mengalikan matrik A dan B (menggunakan for)
*   List item





In [ ]:
#Operasi Matrik

import numpy as np
import sympy as sy

A=np.array([[1, -4, 3],[6, 9, 2],[6, 3, 1]])
B=np.array([[9,-1,3],[6,4,1],[2,-2,1]])
C=np.array([[8,4],[-3,1],[7,4]])
print('A=\n',A)
print('B=\n',B)
print('C=\n',C)

#Penjumlahan Matrik
print('A+B=\n',A+B)
print('B+A=\n',B+A)
print('Hasil A+B = B+A (KOMUTATIF)')

#Pengurangan Matrik
print('A-B=\n',A-B)
print('B-A=\n',B-A)
print('Hasil A-B = B-A (KOMUTATIF)')

#Perkalian Matrik
print('AB=\n',A@B)
print('AC=\n',A@C)
print('BC=\n',B@C)

#Sifat Asosiasi
print('A(BC) =\n',A@(B@C))
print('(AB)C =\n',(A@B)@C)
print ('Hasil A(BC)=(AB)C')

#Perkalian Skalar
c = 5
print('c(AB)\n',c*(A@B))
print('(cA)B\n',(c*A)@B)
print('A(cB)\n',A@(c*B))
print('Hasil c(AB) = (cA)B = A(cB)')

#Perkalian Identitas
i = np.array([[1,0,0],[0,1,0],[0,0,1]])
print('AI=\n',A@i)
print('IA=\n',i@A)
print('A=\n',A)
print('Hasil AI = IA = A')

#Perkalian Nol
print('A0=\n',A*0)
print('0A=\n',0*A)
print('A=\n',A)
print('Hasil A0 = 0A = A')

#Tidak Berlaku Sifat Komutatif
print('AB=\n',A@B)
print('BA=\n',B@A)
print('Hasil AB != BA atau AB tidak sama dengan BA')

#Tranpose Matrik
C_trans = C.transpose()
print('matrik c sebelum di transpose=\n', C)
print('matrik c setelah di transpose=\n',C_trans)
print('ordo C_transpose adalah',C_trans.shape)
z=C_trans@C
print('Z = C_transpose x C =\n',z)
print('ordo z adalah',z.shape)
p=C@C_trans
print('P = C_transpose x C =\n',p)
print('ordo P adalah',p.shape)



A=
 [[ 1 -4  3]
 [ 6  9  2]
 [ 6  3  1]]
B=
 [[ 9 -1  3]
 [ 6  4  1]
 [ 2 -2  1]]
C=
 [[ 8  4]
 [-3  1]
 [ 7  4]]
A+B=
 [[10 -5  6]
 [12 13  3]
 [ 8  1  2]]
B+A=
 [[10 -5  6]
 [12 13  3]
 [ 8  1  2]]
Hasil A+B = B+A (KOMUTATIF)
A-B=
 [[-8 -3  0]
 [ 0  5  1]
 [ 4  5  0]]
B-A=
 [[ 8  3  0]
 [ 0 -5 -1]
 [-4 -5  0]]
Hasil A-B = B-A (KOMUTATIF)
AB=
 [[ -9 -23   2]
 [112  26  29]
 [ 74   4  22]]
AC=
 [[41 12]
 [35 41]
 [46 31]]
BC=
 [[96 47]
 [43 32]
 [29 10]]
A(BC) =
 [[  11  -51]
 [1021  590]
 [ 734  388]]
(AB)C =
 [[  11  -51]
 [1021  590]
 [ 734  388]]
Hasil A(BC)=(AB)C
c(AB)
 [[ -45 -115   10]
 [ 560  130  145]
 [ 370   20  110]]
(cA)B
 [[ -45 -115   10]
 [ 560  130  145]
 [ 370   20  110]]
A(cB)
 [[ -45 -115   10]
 [ 560  130  145]
 [ 370   20  110]]
Hasil c(AB) = (cA)B = A(cB)
AI=
 [[ 1 -4  3]
 [ 6  9  2]
 [ 6  3  1]]
IA=
 [[ 1 -4  3]
 [ 6  9  2]
 [ 6  3  1]]
A=
 [[ 1 -4  3]
 [ 6  9  2]
 [ 6  3  1]]
Hasil AI = IA = A
A0=
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
0A=
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
A=

In [1]:
#Buat program untuk mengalikan matrik A dan B (menggunakan for)
# Matriks A dan B (contoh)
A = [[3, 9], [1, 3]]
B = [[9, 4], [8, 2]]

# Inisialisasi matriks hasil
result = []

# Perkalian matriks menggunakan nested for loop
for i in range(len(A)):
    row = []  # Baris baru pada matriks hasil
    for j in range(len(B[0])):
        product = 0  # Elemen baru pada baris hasil
        for v in range(len(A[i])):
            product += A[i][v] * B[v][j]
        row.append(product)  # Menambahkan hasil perkalian ke baris baru
    result.append(row)  # Menambahkan baris baru ke hasil akhir

# Menampilkan hasil perkalian matriks
for row in result:
    print(row)

[99, 30]
[33, 10]


In [ ]:
import numpy as np
import sympy as sy
A = np.array ([[3,2,1],[6,4,1], [9,1,4]])
B = np.array ([[8,2,3], [3,9,1], [8,4,6]])
C = np.array ([[4,1], [6,1], [1,2]])
D = np.array ([[6,2,8],[1,5,3], [6,3,1]])
G = A @ C
c = 3
C_trans = C.transpose()
Cova = C_trans @ C
print (f"E adalah A+B = \n {A+B}")
print (f"F adalah 2xA = \n {2*A}")
print (f"G adalah AxC= \n {A@C}")
print ("G.shape = ", G.shape)
print (f"H adalah A@(B@C) = \n {A@(B@C)}")
print (f"I adalah (A@B)@C = \n {(A@B)@C}")
print (f"K adalah c*(A@B) = \n {c*(A@B)}")
print (f"L adalah (c*A)@B = \n {(c*A)@B}")
print (f"M adalah A@(c*B) = \n {A@(c*B)}")
print (f"N adalah C Tranpose @ C =", Cova.shape)

E adalah A+B = 
 [[11  4  4]
 [ 9 13  2]
 [17  5 10]]
F adalah 2xA = 
 [[ 6  4  2]
 [12  8  2]
 [18  2  8]]
G adalah AxC= 
 [[25  7]
 [49 12]
 [46 18]]
G.shape =  (3, 2)
H adalah A@(B@C) = 
 [[337 100]
 [612 176]
 [738 254]]
I adalah (A@B)@C = 
 [[337 100]
 [612 176]
 [738 254]]
K adalah c*(A@B) = 
 [[114  84  51]
 [204 156  84]
 [321 129 156]]
L adalah (c*A)@B = 
 [[114  84  51]
 [204 156  84]
 [321 129 156]]
M adalah A@(c*B) = 
 [[114  84  51]
 [204 156  84]
 [321 129 156]]
N adalah C Tranpose @ C = (2, 2)
