##Aljabar Matrik
Tidak mengerjakan tidak boleh masuk

*   Berikan penjelasan tentang apa itu matrik

Matrik A dan C = m x n

Matrik B = n x k
*   Operasi matrik (penjumlahan, perkalian, pengurangan, tranpose)

Perkalian matrik A, B, C, dan c skalar adalah sebagai berikut:

*   A(BC)= (AB)C
*   c(AB)= (cA)B=(cB)A
*   A (B+C) = AB+ AC
*   (B+C)A = BA + CA


*   Buat program untuk mengalikan matrik A dan B (menggunakan for)
*   List item





In [2]:
import numpy as np
import sympy as sy
A = np.array ([[3,2,1],[6,4,1], [9,1,4]])
B = np.array ([[8,2,3], [3,9,1], [8,4,6]])
C = np.array ([[4,1], [6,1], [1,2]])
D = np.array ([[6,2,8],[1,5,3], [6,3,1]])
G = A @ C
c = 3
C_trans = C.transpose()
Cova = C_trans @ C
print (f"E adalah A+B = \n {A+B}")
print (f"F adalah 2xA = \n {2*A}")
print (f"G adalah AxC= \n {A@C}")
print ("G.shape = ", G.shape)
print (f"H adalah A@(B@C) = \n {A@(B@C)}")
print (f"I adalah (A@B)@C = \n {(A@B)@C}")
print (f"K adalah c*(A@B) = \n {c*(A@B)}")
print (f"L adalah (c*A)@B = \n {(c*A)@B}")
print (f"M adalah A@(c*B) = \n {A@(c*B)}")
print (f"N adalah C Tranpose @ C =", Cova.shape)

E adalah A+B = 
 [[11  4  4]
 [ 9 13  2]
 [17  5 10]]
F adalah 2xA = 
 [[ 6  4  2]
 [12  8  2]
 [18  2  8]]
G adalah AxC= 
 [[25  7]
 [49 12]
 [46 18]]
G.shape =  (3, 2)
H adalah A@(B@C) = 
 [[337 100]
 [612 176]
 [738 254]]
I adalah (A@B)@C = 
 [[337 100]
 [612 176]
 [738 254]]
K adalah c*(A@B) = 
 [[114  84  51]
 [204 156  84]
 [321 129 156]]
L adalah (c*A)@B = 
 [[114  84  51]
 [204 156  84]
 [321 129 156]]
M adalah A@(c*B) = 
 [[114  84  51]
 [204 156  84]
 [321 129 156]]
N adalah C Tranpose @ C = (2, 2)
